### ISSUE TITLE
Supporting Remote Meetups -- COVID-19

### ISSUE THREAD

**Issue by SaraJo** [dotnet-foundation/wg-outreach#10]
The .NET Foundation would like to support our local Meetups and community during the current crisis by helping with virtual events. We feel that we have an opportunity to help presenters and organizers pivot to virtual events and handle some of the technical services, fees, and marketing. We’ve discussed some technical options and are soliciting input from the community to figure out next steps.

 

Some options we’ve discussed:

* [Twitch](https://twitch.tv/) – Good streaming platform, but it’s not turnkey. It has some minimum hardware requirements and expertise (e.g. OBS).
* [Zoom](https://zoom.us/) – The Foundation could get a [business or enterprise license](https://zoom.us/pricing), and could [enable YouTube streaming](https://support.zoom.us/hc/en-us/articles/360028478292-Streaming-a-Meeting-or-Webinar-on-YouTube-Live). This seems pretty promising.
* [Discord](https://discordapp.com/store) – The Foundation could get a Nitro account for $99/year and provide HD video streaming. Also seems promising.
* [Teams](https://products.office.com/en-us/microsoft-teams/group-chat-software) – Works well for calls, but requires accounts to create meetings, host meetings, etc. Limited to 250 viewers and doesn’t publish to YouTube.
* [Mixer](https://mixer.com/) – Easy to set up and stream. Limited viewership. Not sure how much Foundation could provide here.
* [YouTube](https://www.youtube.com/c/NETFoundation) – Opportunities to host and promote video after the events, but can’t easily use this as the live platform (requires OBS or another video source).
 

Questions for the community:

1. What would you like to see the .NET Foundation provide to help with virtual events? What are the requirements and opportunities?
2. If you have experience with the above or other virtual event platforms, what are your recommendations?
3. Are you willing to join a virtual team to help with this effort?

**Comment by AhmedKhalil777** [comment]
There are no meetups in our local areas in Egypt, i want to be one of Microsoft's teams that help people to be more productive in Egypt and other places

**Comment by SaraJo** [comment]
@benjaminhowarth1 seems like you can add Restream when you have more info, sounds promising.

**Comment by marco-acorte** [comment]
;) https://github.com/jitsi

**Comment by benjaminhowarth1** [comment]
@SaraJo @marco-acorte I gotta say, the desktop thing looks neat - I like that there's YouTube live streaming. Any idea if it supports Twitch?

**Comment by benjaminhowarth1** [comment]
@SaraJo I'm pretty happy liaising with meetup organisers to set up demo calls with OBS, connect to Restream, then Restream > various other platforms (YT, Twitch, Teams etc.)

**Comment by flcdrg** [comment]
Help would be great. Planning our next meeting online in a few weeks and initial thoughts are to try and use Teams (maybe via my MVP O365 subscription). But definitely interested in guidance or other tools that will work better

**Comment by kilasuit** [comment]
If you went down the Microsoft Teams Route it would need to have Stream allow External Access to recordings, a much asked feature from many MVP's and community members alike and I would push for Live Events to also stream to YouTube as as well, let me kick off some threads with the Teams Product Group about this. 

However I personally don't think a single end medium makes sense and would really like to see a multi stream solution where streams can be pushed across a number of solutions, YouTube, Twitch etc. 

I help organise the PowerScripting Podcast which we currently do live via a mix of Skype calls for those on the podcast and use OBS to stream to YouTube, I also use OBS for streaming occasionally to Twitch too

**Comment by benjaminhowarth1** [comment]
@kilasuit hence why I mentioned Restream - free accounts let you use OBS, push to RTMP, and then Restream does all the auto management to Twitch & YT for you. Even has live chat across all channels - it's why it's a good intermediary for doing recordings so groups can then decide where they want the final output to go.

**Comment by benjaminhowarth1** [comment]
@flcdrg that's why I want a "one-click" sort of solution - something that can live on the wiki here, is minimal hassle, maximum audience reach, low-cost & practical for us to support & for event organisers to use.

**Comment by flcdrg** [comment]
@benjaminhowarth1 yeah.. I want something simple to use.

@kilasuit I was thinking I'd just download the recording from Stream afterwards and manually publish that up to YouTube

**Comment by kilasuit** [comment]
I forgot to mention that yes I would be happy to join a virtual team to help on this.

**Comment by kilasuit** [comment]
> @kilasuit I was thinking I'd just download the recording from Stream afterwards and manually publish that up to YouTube

Feels like a decent feature request to either  automatically do this in the platform its self or make use of functions/logic apps/flow to automate this instead of needing to be a manual task

**Comment by benjaminhowarth1** [comment]
@kilasuit this is why I feel that OBS/Teams + Restream makes a good combo. Teams can output to RTMP, has desktop & screen sharing in the app, and means not everybody watching has to have a Teams account, providing somebody keeps an eye on the aggregated Restream comments. I'm sure there are other Xstreaming platforms too, I'll make some more enquiries tomorrow morning.

**Comment by flcdrg** [comment]
@benjaminhowarth1 have you got this written up somewhere? It does look interesting

**Comment by douglasstarnes** [comment]
I'm happy to help in whatever way I can.  I am involved with 4 UGs in the Memphis, TN area and all of them are going virtual so we are going to be experimenting.  Right now from my POV it's a toss-up between Teams and Zoom. I've ruled out YouTube and as much as I like Twitch, I don't think it's best for encouraging interaction other than between the presenter and the audience.  I like the feature of Zoom to have the 'virtual breakout' but the free version has a duration limit.  Again, I'd love to help because I see this as an opportunity that can benefit the community even after the pandemic subsides.  Virtual events are easier to attend so it could reach a whole new audience that didn't even know about the community.

**Comment by douglasstarnes** [comment]
After reading through some of the above comments I have mixed feelings about streaming to multiple platforms as they will all give the viewer different experiences.  One of the benefits of the in person meetup is that everyone looks at the same screen from the same perspective and in the same room so they interact with each other the same way.  How would someone watching on YT interact with someone on Twitch or Teams?  The idea of the community meetup is not to just go watch the presentation silently, get free pizza and then go home.  It's to start a discussion.  That's my biggest challenge is how to encourage the interaction and  discussion beyond the presentation.

**Comment by benjaminhowarth1** [comment]
> @benjaminhowarth1 have you got this written up somewhere? It does look interesting

The setup I've done myself and to be honest, I've only done it once, but I'm gonna do some more livestreaming in the coming days and weeks, and play with the setup until I've got it down, then I'll blog it, and write up a more professional setup for the wiki here.

**Comment by ozkary** [comment]
Perhaps s partnership with other companies could help in times of crisis. Google meets is a good platform. Let's partner with them and get a free access for this bad time.  Let's use tech for health and good and tear down walls of domain differences.

**Comment by GuruCharan94** [comment]
We are planning to try [Microsoft Teams Live](https://docs.microsoft.com/en-us/microsoftteams/teams-live-events/what-are-teams-live-events). 
One of the organizers is an MVP and so has the required license.

Teams live can host upto 10000 attendees and an event can last for 4 hours and has a moderated Q&A (only text). See [here for the features available](https://docs.microsoft.com/en-us/microsoftteams/teams-live-events/plan-for-teams-live-events)

**Comment by vnwonah** [comment]
3. Willing to join a virtual team to help with effort.

**Comment by salmanmkc** [comment]
We host events on YouTube, streaming from Teams, like this [(http://wit.mspinspire.com)]

**Comment by salmanmkc** [comment]
We host events on YouTube, streaming from Teams, like this [](http://wit.mspinspire.com)

**Comment by salmanmkc** [comment]
We host events on YouTube, streaming from Teams, like this [Women in Tech Week with Miri Rodriguez, head of Global Internships at Microsoft](http://wit.mspinspire.com)

**Comment by nikneem** [comment]
Willing to join a remote team! We have some experience with zoom is a real good platform for this.

**Comment by benjaminhowarth1** [comment]
Restream have gotten back to me & are offering 20% off their paid plans. Suggest we use @clairernovotny's Mailchimp list to distribute these to meetup organisers rather than post the code here. Can someone volunteer to run a dummy test with me through Teams so I can test a Teams/OBS/Restream setup?

**Comment by bsstahl** [comment]
For a virtual hackathon, such as a [GiveCamp](https://givecamp.org/) event, it seems like the always-on, team-focused nature of Discord would be very useful. For meetups, I think Zoom is the best I've used so far but there are certainly similar tools that I haven't yet used. In both cases, the Foundation providing the tools for the groups would be very helpful, more so for Discord where many of us don't have access to a paid version. For Zoom, there is often someone who has access to an Enterprise instance, at least in my experience. We will be trying a Zoom meeting next Thursday at the Phoenix area .NET User Groups and will report-back on how it goes.

**Comment by apead** [comment]
Tested MS Teams Live Events yesterday.   It supports 10 000 anonymous,  public attendees.   That should be enough. 😁    We are going to try that for meetups when necessary.

**Comment by jamesmontemagno** [comment]
I would group these into 3 categories:

1.) Live streaming public -> Twitch, YouTube, Mixer, etc.

Any of these are "live" to the internet and usually completely public. They require a constant connection and pretty decent upload speed (I recommend 10 MBPS minimum). They are also more complex to stream yourself and also have someone join you to get the audio/video correct. There is also the worry of leaking your own PII accidentally out to the world as you are sharing screens and going live (a constant fear of mine). The software used, usually OBS, is fantastic, but not always user friendly. To interact users need to register for an account and at the same time anyone can join including spam bots that can be annoying.

While I would love everyone live streaming and putting content out there, I believe there is a larger learning curve, more error prone, and sort of loses the "local" community vibe. You do have complete control of the stream though, which is nice.

2.) Meetings -> Teams, Google Meet, Zoom, etc

These platforms offer more of a pre-schedule private link for users to join in and do a call. Screen sharing is built in for the hosts, audio setup is easier, and usually bandwidth is more dynamic for streaming. Most of them also have a way of recording the session so you can export it later. 

The downside of these is that people join in and technically anyone can talk/turn on webcam. On the plus side you get to keep the meeting more private and to your user group if you desire. There are limits sometimes to them, which for most user groups probably wont be an issue.

3.) Webcast/Hybrid -> Teams Live Events, GoToMeeting, etc
These sit in the middle where you still have a private link and stream, but you don't have to worry about people joining in and turning on their webcam. They have higher limits, still allow interaction, but you have full control. 

This would be my recommended route if I was doing it for my user group. Personally, I would use Teams because it has built in Closed Captioning, which is important to me to be inclusive of all group members. 

Reading this thread though I think what is clear is that probably requiring or offering a single solution isn't ideal. Having a list of options and allowing group leaders to pick their route based on the information would be ideal. Hopefully that list offers some free subscriptions to group leaders through this program.

**Comment by douglasstarnes** [comment]
I agree with @jamesmontemagno .  My comment earlier that I was reluctant to advocate multiple platforms was in reference to a single event.  If you have a single event with one group on YT and another on Teams, how are they going to interact?  Even worse, the presenter has to deal with two different audiences (or more) on two different interfaces and so on.  Streaming on multiple platforms for a single event (especially small ones like meetups) may be more trouble than it's worth IMO.  But I definitely am in favor of assisting groups to find the right platform for their event.  Maybe we could form some guidance around that?

**Comment by jamesmontemagno** [comment]
^ Agree here, I do not recommend streaming or doing multiple platforms at all. We do it for .NET Standups because I spent a crazy amount of time setting up the studio and have  been streaming for over a year. Even personally though I only stream on Twitch, multiple is too complex.

Again I think the Hybrid/Webinar solution is the best for user group meetups.

**Comment by nikneem** [comment]
In my believe this thread is about meetups and meetings. We're currently missing events and meetups. I believe live coders and Webcasts are still done and those people already use their preferred platform and won't change that. It's the meetups and events we're missing and this initiative is there to fill that gap (again, that's my assumption). So how can we have a couple of speaker present cool features and give their sessions, allowing attendees world wide to join without a complicated registration procedure. Again, I'm very willing to help and think about how to shape this environment...

**Comment by apead** [comment]
@jamesmontemagno  MS Teams Live events does anonymous public live events.  You can limit attendees to just be able to do Q&A. It also has an approval process for Q&A.   So that feature falls into the "Live streaming public " category you have.

**Comment by douglasstarnes** [comment]
I like the approval process for Q&A and also noticed that yesterday Teams added a raise hand feature which was missing.  Zoom still has virtual breakouts but for small events (ie. meetups) that might not be a requirement.

**Comment by pmgower** [comment]
> If you went down the Microsoft Teams Route it would need to have Stream allow External Access to recordings, a much asked feature from many MVP's and community members alike and I would push for Live Events to also stream to YouTube as as well, let me kick off some threads with the Teams Product Group about this.
> 
> However I personally don't think a single end medium makes sense and would really like to see a multi stream solution where streams can be pushed across a number of solutions, YouTube, Twitch etc.
> 
> I help organise the PowerScripting Podcast which we currently do live via a mix of Skype calls for those on the podcast and use OBS to stream to YouTube, I also use OBS for streaming occasionally to Twitch too

I would also suggest not going just the Microsoft Teams route.  I tried to join a Teams meeting last night but it kept telling me that my Teams account needed to be approved by my admin.  I am the admin and it's my personal account so apparently there's a mixup or setup issues with my account but I couldn't even join my friend's meetup last night because of this issue.  

The beauty of Zoom or some streaming platform (Twitch, Youtube, etc.) is that anyone can watch / attend without an account.  

@SaraJo I am willing to join a virtual team to help with this effort.

**Comment by apead** [comment]
@pmgower Teams Live Events has a policy you can set and then it's fully anonymous.. ie, no account needed.

**Comment by jamesmontemagno** [comment]
@apead I think as them as a bit different as you still have a link that you can send people and you can make that private on a meetup. Yes other people can join, but you have more control. Also I don't put it in the live stream category as it doesn't require a full OBS setup.

**Comment by SaraJo** [comment]
Hey all, sounds great. Thanks for being part of the planning team for this. It seems like most people are in agreement that Microsoft Teams is a good place for this. We can look into the process of licenses (@clairernovotny, I believe you mentioned that it's possible we will be able to get through the foundation? Will send an email so we can work out details).

**Comment by SaraJo** [comment]
Hello to this group, two things:

1) Claire has been reaching out to get info about our Teams membership and if it can support this. No word back yet. Does anyone have a contact there? If not, do we have a second choice?

2) What's the best way to organize the working group about this, there are a lot of folks here that have offered to help and I want to ensure we can get this moving well. We can keep this in an issue, we can start a new discussion, we can start a chat on Teams. LMK what you think, thank you!

**Comment by nikneem** [comment]
> Hello to this group, two things:
> 
> 1. Claire has been reaching out to get info about our Teams membership and if it can support this. No word back yet. Does anyone have a contact there? If not, do we have a second choice?
> 2. What's the best way to organize the working group about this, there are a lot of folks here that have offered to help and I want to ensure we can get this moving well. We can keep this in an issue, we can start a new discussion, we can start a chat on Teams. LMK what you think, thank you!

Hi @SaraJo
Again, I believe Zoom is an excellent alternative so I suggest you contact the Zoom guys as well.

**Comment by douglasstarnes** [comment]
In Memphis, the .NET, Office 365 and Power Platform UGs have gone with Teams.  The O365 group was using it before.  Tonight during a discussion with the (unofficial) .NET UG board we came to the conclusion that Teams was best for us because 1) the local Microsoft office is hooking us up and 2) it requires no download for the browser client.  Last week when I joined a Zoom call on a new machine for the first time, it prompyed me to download a shim.

**Comment by frankodoom** [comment]
We are deciding to go with Teams because our .NET Community has a Teams channel that we invite members to when they Join. We are planning to have our first Virtual Meetup which will also be made available on-demand for those who couldn't attend and want to watch later. I just hope Teams Community doesn't pose some restrictions for us to achieve this.

**Comment by frankodoom** [comment]
> The .NET Foundation would like to support our local Meetups and community during the current crisis by helping with virtual events. We feel that we have an opportunity to help presenters and organizers pivot to virtual events and handle some of the technical services, fees, and marketing. We’ve discussed some technical options and are soliciting input from the community to figure out next steps.
> 
> Some options we’ve discussed:
> 
> * [Twitch](https://twitch.tv/) – Good streaming platform, but it’s not turnkey. It has some minimum hardware requirements and expertise (e.g. OBS).
> * [Zoom](https://zoom.us/) – The Foundation could get a [business or enterprise license](https://zoom.us/pricing), and could [enable YouTube streaming](https://support.zoom.us/hc/en-us/articles/360028478292-Streaming-a-Meeting-or-Webinar-on-YouTube-Live). This seems pretty promising.
> * [Discord](https://discordapp.com/store) – The Foundation could get a Nitro account for $99/year and provide HD video streaming. Also seems promising.
> * [Teams](https://products.office.com/en-us/microsoft-teams/group-chat-software) – Works well for calls, but requires accounts to create meetings, host meetings, etc. Limited to 250 viewers and doesn’t publish to YouTube.
> * [Mixer](https://mixer.com/) – Easy to set up and stream. Limited viewership. Not sure how much Foundation could provide here.
> * [YouTube](https://www.youtube.com/c/NETFoundation) – Opportunities to host and promote video after the events, but can’t easily use this as the live platform (requires OBS or another video source).
> 
> Questions for the community:
> 
> 1. What would you like to see the .NET Foundation provide to help with virtual events? What are the requirements and opportunities?
> 2. If you have experience with the above or other virtual event platforms, what are your recommendations?
> 3. Are you willing to join a virtual team to help with this effort?

Any known restrictions for the Teams Community Edition

**Comment by benjaminhowarth1** [comment]
> > The .NET Foundation would like to support our local Meetups and community during the current crisis by helping with virtual events. We feel that we have an opportunity to help presenters and organizers pivot to virtual events and handle some of the technical services, fees, and marketing. We’ve discussed some technical options and are soliciting input from the community to figure out next steps.
> > Some options we’ve discussed:
> > 
> > * [Twitch](https://twitch.tv/) – Good streaming platform, but it’s not turnkey. It has some minimum hardware requirements and expertise (e.g. OBS).
> > * [Zoom](https://zoom.us/) – The Foundation could get a [business or enterprise license](https://zoom.us/pricing), and could [enable YouTube streaming](https://support.zoom.us/hc/en-us/articles/360028478292-Streaming-a-Meeting-or-Webinar-on-YouTube-Live). This seems pretty promising.
> > * [Discord](https://discordapp.com/store) – The Foundation could get a Nitro account for $99/year and provide HD video streaming. Also seems promising.
> > * [Teams](https://products.office.com/en-us/microsoft-teams/group-chat-software) – Works well for calls, but requires accounts to create meetings, host meetings, etc. Limited to 250 viewers and doesn’t publish to YouTube.
> > * [Mixer](https://mixer.com/) – Easy to set up and stream. Limited viewership. Not sure how much Foundation could provide here.
> > * [YouTube](https://www.youtube.com/c/NETFoundation) – Opportunities to host and promote video after the events, but can’t easily use this as the live platform (requires OBS or another video source).
> > 
> > Questions for the community:
> > 
> > 1. What would you like to see the .NET Foundation provide to help with virtual events? What are the requirements and opportunities?
> > 2. If you have experience with the above or other virtual event platforms, what are your recommendations?
> > 3. Are you willing to join a virtual team to help with this effort?
> 
> Any known restrictions for the Teams Community Edition that can limit its usage for virtual meetups?

Yes. Events can't be scheduled in advance, live streams aren't supported, & guest access is extremely limited, I've already tested with an instance I set up myself.

**Comment by SaraJo** [comment]
Still no word from MS regarding teams. Also tried starting this conversation in our teams instance and can't find most of ya'll's IDs. It seems like this problem is two pronged:

1) find a solution for remote hosting that works for all meetup organizers
2) add a page to the website where people can find remote meetups

I was thinking of starting work on #2 while we are still processing #1, I know there are some meetups already running remotely that we could share. Would anyone be into collaborating?

**Comment by benjaminhowarth1** [comment]
@SaraJo gladly. Last meetup I ran was with Zoom, but I've done Twitch live-streaming before as well, which went to FB, Periscope & YouTube.

**Comment by SaraJo** [comment]
@benjaminhowarth1, sounds great. Maybe we can compile a list of possible resources and send to the organizers?

**Comment by frankodoom** [comment]
> Still no word from MS regarding teams. Also tried starting this conversation in our teams instance and can't find most of ya'll's IDs. It seems like this problem is two pronged:
> 
> 1. find a solution for remote hosting that works for all meetup organizers
> 2. add a page to the website where people can find remote meetups
> 
> I was thinking of starting work on #2 while we are still processing #1, I know there are some meetups already running remotely that we could share. Would anyone be into collaborating?

My Teams Id f.odoom@outlook.com :-)

**Comment by frankodoom** [comment]
> @SaraJo gladly. Last meetup I ran was with Zoom, but I've done Twitch live-streaming before as well, which went to FB, Periscope & YouTube.

I am sure this is a Zoom Pro Account,  the free tier has a restriction of 45 minutes i guess.

**Comment by benjaminhowarth1** [comment]
@frankodoom yeah, I realised that with 10 minutes to go & had to quickly upgrade! The Foundation bulk-purchasing a Zoom license doesn't logistically work either.

**Comment by jamesmontemagno** [comment]
Put together a little video one using Teams Live Events: https://www.youtube.com/watch?v=m85ZGXF06vk

Worked out nice. Jon and I both have Teams accounts at MS so it worked nicely (also could record them). I think as long as a user has a Teams account they can present and host them too. We will be using this next week: https://www.meetup.com/SeattleMobileDevelopers/events/269755021/

@sarajo you may be able to query the meetup API to see if it is an online meeting event type. They have a new check box, and I assume their API would return that.

**Comment by nikneem** [comment]
I was one of the speakers at the Virtual Azure Community Day on the 31st of March (https://azureday.community). They hosted 4 tracks with 8 speakers on each track, so an online event with 32 speakers all remote from their own living room. They used Skype, which sends out two streams (one cam and one shared screen) which is mixed with OBS and then sent to restream. Restream can then broadcast the stream to a huge amount of streaming services (Youtube, Facebook, twitch, you name it). They used an approach blogged by Henk Boelman. I really experienced this very good as a speaker and I believe it was well-received by attendees.

https://www.henkboelman.com/articles/online-meetups-with-obs-and-skype/

**Comment by jongalloway** [comment]
There's a lot of good information in this thread. I'd be happy to send a pull request to create a one page markdown doc to summarize, and people can collaborate on that. 

Since this repo is mostly for working group discussions, I'm thinking a markdown doc in https://github.com/dotnet-presentations/dotnet-presentations.github.io would make sense.

Sound good @SaraJo @clairernovotny ?

**Comment by SaraJo** [comment]
That sounds amazing, thank you, @jongalloway!!

**Comment by SaraJo** [comment]
@jongalloway were you able to make any headway on this? Next outreach group meeting is tomorrow.

**Comment by eriklieben** [comment]
One tool that is missing in the above is https://streamyard.com/

You could kinda see it as OBS in the browser, if you don't want to setup OBS, Skype with NDI, etc. and re-stream. 

It's limited if you compare it to OBS, but does enough to make it work. Looking at the images and format, I guess this livestream is hosted used the above tool: https://youtu.be/B8kd33nUdcA

For 20/25 euro a month you can re-stream to 2 destinations, for example YouTube and twitch. 
That's probably a decent amount to pay, if you don't want to setup OBS, etc. 

And a sponsor that is normally paying a few hundred euro's towards food for a meetup, can probably easily help out sponsor that amount in return for a few minutes of speaking time or a placed logo during the event right? In the same way as one would do with a in-person meetup only now it's way cheaper for them :-)

**Comment by jongalloway** [comment]
I haven't yet - I'll be at the outreach meeting, we can ask for feedback on what info people want to see in the doc and I can write it up later today.

**Comment by naeemakram** [comment]
Just today I my university professor cousin called me asking the same questions. I showed her how to use Zoom for delivering her M.Phil classes. Inside our office we're using Microsoft Teams but it's licensing is complex so I don't recommend Foundation using Teams unless Microsoft provides us some relief. 
Yes, I'd love to be a part of such a meetup.

**Comment by jongalloway** [comment]
After more discussion based on what @jamesmontemagno and I have been doing with the .NET Community Standups and what's worked at James' local Meetup, he had a good idea that I think simplifies things quite a bit by not requiring each Meetup to become virtual event / live streaming experts.

Proposal here: [Creation of Official ".NET Virtual Meetups" User Group](https://github.com/dotnet-foundation/wg-outreach/issues/12)

**Comment by flcdrg** [comment]
I've been talking a lot to my fellow MVPs in the Australia & New Zealand region - especially listening to those who's expertise is in Teams and such.

I've been using a combination of my MVP Office 365 tenancy, and also signed our group for an O365 Business Essentials subscription (only to discover that it doesn't support Live Events). We've run both Teams Live Events and Teams Meetings successfully so far.

Going back a few years, Microsoft used to offer user groups free O365 licenses. If there was a way for the .NET Foundation to enable that (I gather an E1 license would cover Live Events), that would be great.

I'm not sure about having a ".NET Virtual User Group". I can see some advantages, but I wonder if it would also encroach/supercede existing user groups. Wouldn't it be better just to enable/facilitate existing groups rather than create a new "super" user group?

**Comment by douglasstarnes** [comment]
In Memphis we’ve been using a combination of Live Events and regular Teams meetings. In fact, I just got done after a 2 hour ‘sound check’ to make sure everything was set for a UG tomorrow.  Once you get everything set up, Teams is awesome. Setting Teams up, as we learned tonight can be a challenge. Still I like the fact that to be an attendee that you don’t have to install or login.  Just click a link and you are connected. As far as virtual used groups there are advantages and disadvantages. It’s harder to keep people engaged.  They have less incentive to show up, no free food. My plan is to have hybrid meetups for a while because some people will be reluctant to come to a physical meeting even after in person meeting start again. But I want to resume the physical meetings as soon as possible. So I don’t see the virtual meetup as something to replace the existing events.

**Comment by jongalloway** [comment]
@flcdrg I commented on the issue as well, but I don't see these as necessarily being exclusive. The .NET Foundation would essentially be hosting your existing user group, helping to stream and promote it. So the event could be listed on both Meetups, and listed as "Scottsdale .NET User Group, Hosted by the .NET Foundation Virtual User Group". That could be good for rotating through event organizers, local speakers, etc. Personally, if a group didn't want an event to also be listed under the .NET Foundation Virtual Meetup, I would think that would be fine.

**Comment by goh-chunlin** [comment]
For Singapore side, we followed the preference of the speakers and thus we somehow had tested with several platforms. Please refer to the recordings for performance:

YouTube + OBS + Whereby: https://www.youtube.com/watch?v=yhSTu93kYrs
YouTube + OBS + Google Hangout: https://www.youtube.com/watch?v=YNqtC2K0HLI
YouTube + OBS + Microsoft Teams: https://www.youtube.com/watch?v=W3EfIoQN0ew
YouTube + OBS + Skype: https://www.youtube.com/watch?v=Y0W4o0YjC9g

So far we have tried with UK, US, Japan, and Malaysia speakers. Hopefully our Singapore team can input some of our past experience and challenges that we encountered in the live streaming.

What I'd like to share now for your reference is that the workflow of our live streaming is as follows:
- Host needs to give an introduction about the meetup;
- Host will introduce the speakers and their profiles+topics;
- Speaker take turn to talk, I will change the screen to focus at the speaker only when the speaker is speaking;
- Each speaker will end his session with a Q&A by answering questions on the YouTube live chat;
- Each speaker has 30-40 minutes for his/her topic;
- I will change the screen to focus at next speaker after the current one ends;
- Next speaker speaks;
- I will take back the screen to me after all speakers finish presenting and do a closing;
- Recording will be available automatically after YouTube processes the live streaming.

**Comment by maurobennici** [comment]
Almost all the meetings and meetups, principally in Italy, were made with Zoom. It is considered a neutral platform with respect to Teams and Meet.

**Comment by kilasuit** [comment]
> Going back a few years, Microsoft used to offer user groups free O365 licenses. If there was a way for the .NET Foundation to enable that (I gather an E1 license would cover Live Events), that would be great.

I would hope something along these lines would be forthcoming - we shall see what the Teams Team may provide in the future

> I'm not sure about having a ".NET Virtual User Group". I can see some advantages, but I wonder if it would also encroach/supercede existing user groups. Wouldn't it be better just to enable/facilitate existing groups rather than create a new "super" user group?

The virtual aspect of the user group is just an extension of a physical event allowing anyone to attend from anywhere & wouldn't encroach on the existing event. which would happen anyway, virtual is just an additional benefit & allows for wider inclusivity    

We can also make use of tooling available via restream (for livestreams of video) & matterbridge (https://github.com/42wim/matterbridge) for chat in which ever tools of choice. which I know is already in use in the PowerShell community

I think there will be some blending of all tech required to properly meet the supporting of remote meetups

**Comment by SaraJo** [comment]
All, 

   Tonight we tested our first remote meetup. It went smoothly, and we are ready to add more. More info below. 

To submit your user group session, get scheduled, get promoted, and have your user group event hosted on the foundation's You Tube simply add a new issue to this repository. There is a template setup for User Group events. You can see an example in issue #14. 

If you are looking for awesome upcoming user group sessions from around the world? Then join the [.NET Virtual User Group](https://www.meetup.com/dotnet-virtual-user-group) today!

**Comment by SaraJo** [comment]
Closing this issue as we have our Virtual User Group setup!
