### ISSUE TITLE
Solution2 - C# Discord Conference

### ISSUE THREAD

**Issue by Perksey** [dotnet-foundation/wg-outreach#101]
## Title: 
Solution2 - C# Discord Conference

## Description:
An event that the C# Discord server is hosting called Solution2. This is the second conference they’re hosting, the first being Solution1 for which the archive can be found on their YouTube channel: https://www.youtube.com/playlist?list=PLykyx5HcHRdbVXR8PYtcco52T9eN7nAPc

Various Microsoft employees/.NET team members hosted talks, including Scott Hanselmen, Fred Silberberg, and Tanner Gooding to name a few. The idea is to give this community Discord server, typically informal in nature, to educate one another and promote what they’re doing on a bigger and more formal platform. As a result, topics can vary wildly so long as they remain .NET related. It aims to capture the spirit of both the Discord community and the .NET ecosystem.

The .NET Foundation has supported the C# Discord in the past, and is responsible for the hosting of its moderation services and infrastructure - there is an established relationship here. Solution1 was sponsored by JetBrains and is likely to be the case for Solution2 as well.

The main reason I’ve been asked to reach out is to see whether the .NET Foundation would be willing to host the YouTube streams on their YouTube channel. All participants are those in good standing with both the C# Discord server (and usually a formal Associate of the server) and the .NET Foundation (code of conduct wise). The reach on the YouTube channel that was spawned for this event was relatively low, and I really feel like we should be doing all we can to promote the great things the community can independently create such as these events.

I figured given that there is an established relationship, it’s more .NET content, and the Marketing Committee have promoted Solution1 in the past that this should be a pretty unobjectionable thing.
If this is approved Nicole would need to give the members of the Discord access to the YouTube channel to create the streams. Please contact me separately for the details of the members to add.

**Note: The existing Virtual User Group processes are not applicable here given that as it stands we'd have to submit the form for each speaker, meaning we could end up submitting 20+ forms. Moreover, we don't want to use the DNF's StreamYard infrastructure as we already have our own and this would just be an unnecessary expense to the Foundation. Metadata is also not yet known on the event, and it would be more appropriate to have the ability to create the streams ourselves given all of this. Which is why we're requesting a channel manager be added, similar to the Marketing Committee did for Silk.NET, rather than a one-shot stream link as that could get chaotic.**
 
## Measure of impact:
52,423 Discord members

## Requested Budget:
$0

## Size of the Committee Requested:
0 volunteers

## Which Goal and Priority is this project aligned with:
All goals. No priorities have been established yet.

## How will we know this outreach is successful?
Event participation, viewership growth overtime

**Comment by nicoleabuhakmeh** [comment]
Hi Dylan,  Silk Project - teamsilk.net@gmail.com is already listed as a Manager on the DNF YouTube account - Can you confirm you have access to that account.

**Comment by Perksey** [comment]
Silk.NET does indeed have access, however the Solution2 conference is being organised by another set of people (the C# discord), for whom they have a primary contact (which I can send over email) who would require access so that they don't have to go through me to setup the streams - I'm not the primary organiser, I'm just helping them coordinate things like this.

**Comment by nicoleabuhakmeh** [comment]
Great, adding @glennawatson to this conversation for the support.  We can point them here once they get the dates and everything set up for promotion: https://github.com/dotnet-foundation/content/issues/new/choose

If we get the dates, we can at least coordinate with the individuals that set up the streaming - to be sure we don't have anything else scheduled on that day.

**Comment by Perksey** [comment]
The dates, while unannounced as of yet, are set as 17th to 24th of November 2024. Hope this helps. Glenn has the email address of the contact from the C# server. Promotion will occur similar to last time as you have indicated (dotnet-foundation#105 for last time's promotion)

**Comment by nicoleabuhakmeh** [comment]
Perfect. I've added the individuals for the Youtube access. 
<img width="620" alt="Screenshot 2024-09-02 at 10 04 34 AM" src="https://github.com/user-attachments/assets/ba789506-497d-48e8-bbcd-ba6bd0fc8271">

Looking forward to hearing more and sharing the event. - Nicole

**Comment by Perksey** [comment]
Thanks! I've been told they've been received, so I'll close this and will open amplification issues in the content repo as we move closer to the event :)

Thanks again for all of your help!

**Comment by nicoleabuhakmeh** [comment]
Hey @Perksey  -  we met at the outreach committee today and discussed the event. I'm going to reopened it for maintenance. Let's use this for any issues that come up as we move closer to the date and so we don't double schedule anything on the dates once they are known. 

Tagging @codehippie1 regarding the note about the User Group. Using their own Streamyard but would like to stream on our YouTube. Let's make a note to make sure any permissions might need changed back after the event when it comes to Streamyard.
