### ISSUE TITLE
Creation of Official ".NET Virtual Meetups" User Group.

### ISSUE THREAD

**Issue by jamesmontemagno** [dotnet-foundation/wg-outreach#12]
Submitting this with @jongalloway

## Title: 

Creation of Official ".NET Virtual Meetups" User Group.

## Description:

To keep our community going and engaged during these times user group leaders have done a fantastic job throwing virtual events. However, it is still challenging for many groups to continue to do family, time, and complexity when it comes to streaming a live meetup event. Some of the challenges:

* Each user group has to invest the time in developing virtual event expertise
* User groups may also need to deal with costs for streaming services or equipment
* User groups may also be unnecessarily competing for viewers, rather than working with a coordinated schedule
* Each user group's marketing reach is likely local, while virtual events have the potential of reaching a global audience
* In addition to viewership, virtual events have the ability to invite international speakers, but may not have the connections to reach them
* While it's possible to add user group presentation recordings to a playlist on the .NET Foundation YouTube channel, it requires some manual work to review and add them which would introduce delay

Introducing the .NET Virtual Meetups user group would give user groups and community members the ability to host and present at a virtual .NET User Group with ease. Each week a virtual meetup would be scheduled and streamed to the .NET Foundation YouTube channel on .NET specific topics. Topics can be proposed via GitHub using a proposal template by any .NET User Group or community member that wishes to present at the virtual meetup. The .NET Virtual Meetup committee would process proposals once a week and approve meetups that would be schedule on Meetup.com and the .NET Foundation YouTube channel.

The .NET Virtual Meetups would be a compliment to existing user groups. During time of virtual only events it gives local user group leaders the ability to give further visibility to their user group and to their presenters. After this time when in-person events can continue, so would the .NET Virtual Meetups with the capability of co-hosting in-person meetups. Additionally, as part of the main announcements during the virtual meetup can be to announce upcoming local events around the globe.

### Day of Flow:
On the day of the event the presenter would call in to the meetup host via Skype who would then do the transmission to YouTube via OBS. At the start of the call would be general .NET/.NET Foundation announcements by the host and then followed by the presentation. The host would monitor the chat room for questions throughout and relay them to the presenter.

At the end of the call the video would be auto-archived into a YouTube playlist for future playback.

Work to be done outside of the events:
* Setup a Meetup.com user group called ".NET Virtual Meetups" under the .NET Foundation
* Setup a GitHub repo with a template for proposal
* Schedule weekly triage of proposal and schedule future events
* Update the .NET Foundation with a "Virtual Meetups" section (similar to http://live.dot.net)

## Measure of impact:
* Weekly .NET Virtual Meetups with an average of 300 attendees to start.
* On demand video generation of 3,000.
* Promotion to the 18,000 .NET Foundation's YouTube subscribers and social media channels.
* Perception change by bringing significant community generated content to the .NET Foundation channel.
* Potentially paving the way for larger virtual events or other YouTube channel usage once we demonstrate the potential to the community.
* Opening up speaker opportunities to present to a global audience.

## Requested Budget:

The only additional cost would be the price of the meetup page.

## Size of Committee Requested:

3 volunteers, to triage and schedule meetups. Additionally, they would be setup to host.

## Which Goal and Priority is this project aligned with:

- Encourage new developers to build with .NET
- Keep user groups and community going during these times and beyond.
- Promote local user groups during announcements and co-hosting events.

## How will we know this outreach is successful?

From the number of on going virtual meetups and live attendees.

**Comment by cecilphillip** [comment]
@jamesmontemagno  Is there a way to leverage the existing [.NET Foundation pro account,](https://www.meetup.com/pro/dotnet/) as opposed to created a new thing on Meetup .NET.

From the perspective of UGs that already have Meetup pages, as a member it would be nice to just register for an event under my existing meetup and then have the Foundation assist with the streaming logistics. If I become interested in other events, then I can just go see what else is happening via the Pro account.

**Comment by jamesmontemagno** [comment]
So, perhaps I didn't make the goal super clear, but it would be a way to have a single unified ".NET Virtual User Group" that is run by the foundation. This way the committee runs it, onboards presentations, etc. Local user groups would still meet and do their own things, but this gives developers all over the globe one single place to go for Virtual meetups even when this is all voer.

**Comment by jongalloway** [comment]
I don't think they'd necessarily need to be exclusive, either. For instance, let's say the the London .NET User Group lines up a speaker for a talk, they could register it with the .NET Virtual User Group too. They could promote on their Meetup, but would also get event promotion and streaming through the .NET Foundation's .NET Virtual User Group. Not sure what the wording would be, but something like "This next Friday the .NET Foundation is hosting the London .NET User Group".

**Comment by SaraJo** [comment]
This is amazing. I'd be interested in volunteering. I know we have a group working on how to accept proposals so we may be in limbo. @clairernovotny, have any ideas?

**Comment by jamesmontemagno** [comment]
Yes that is exactly what i was thinking @jongalloway, like you could do both and I think after all of this it would be great to keep things like that going as you would basically be highlighting .NET user groups each week.

**Comment by frankodoom** [comment]
@jamesmontemagno @jongalloway  I think this is a good idea, instead of vetting which meetup should be added to the .Net Foundation's Youtube page the .Net Virtual Meetup will be a good way to give each meetup around the globe an opportunity to be connected and heard and opening up speaker opportunities to present to a global audience is definitely awesome! Even though in Africa Data is quite expensive and not everyone has access to fixed broadband we will see how best we can rally this here.

**Comment by jamesmontemagno** [comment]
I added a little blurb:

```
The .NET Virtual Meetups would be a compliment to existing user groups. During time of virtual only events it gives local user group leaders the ability to give further visibility to their user group and to their presenters. After this time when in-person events can continue, so would the .NET Virtual Meetups with the capability of co-hosting in-person meetups. Additionally, as part of the main announcements during the virtual meetup can be to announce upcoming local events around the globe.
```

**Comment by jamesmontemagno** [comment]
@frankodoom for sure! The nice part about YouTube archives is that local members in your area would be able to download at reduced size. Also, YouTube also lets you set the stream quality level so that is another option. A challenge there (and even here in the states as upload speed can be a challenge) is to make sure we test out everyone's connections.

**Comment by benjaminhowarth1** [comment]
I'm happy to work with EMEA groups as host (I run Canary Wharf .NET) & record with OBS to Youtube & Twitch.

**Comment by NeelBhatt** [comment]
Redirected here from the email chain of "Vetting Remote Meetups for the .NET Foundation YouTube" Nice initiative and looking forward to be a part of this group.

**Comment by SaraJo** [comment]
All, we'd like to kick this initiative off so we can get these Meetups featured. We would put proposals for meetups to be featured in a folder on this repo. 

Please chime in by EOD Friday if there are any objections. Thank you for your partnership on this.

**Comment by haacked** [comment]
I love this idea! I just spoke at a virtual user group meeting that wasn’t set up to post recordings online. We could make sure to have that set up.

P.s. @jamesmontemagno i think the word you’re looking for is “complement” and not “compliment”. 😝

**Comment by kulov** [comment]
Please consider that there are many existing UGs today that are not using meetup accounts still. I do not see any reason why we should promote a paid service (meetup.com) vs free one like Eventbrite.com. The later has integrated ticket booking within the Facebook event itself which makes it much preferred option to communities I run in Bulgaria. Did I mention - it is free :)

One thing our co-leaders are having issues with is how to properly do live streaming to FB, YouTube, others simultaniously. Teams just recently run TTT campaing - we can do something similar with the focus of streaming to social media platforms. DNF pointed group of streaming experts for non critical technical support whould be of great help IMHO.

Finally - some support on graphical design tips/tricks/tools would help me great personally. I can provide help to other group leaders on how to use PowerPoint master templates to author presentations more professionally.

**Comment by jamesmontemagno** [comment]
So, the goal is that the .NET Virtual User Group is setup to support any and all user groups no matter what platform they are using to organize. If they have a speaker that wants to present at their user group they can schedule it like normal. But then they put in a proposal to make it an official .NET Virtual User Group and then it is posted on the meetup.com page for .NET Virtual User Groups that anyone around the globe can join. Then there is a scheduled private stream on YouTube that the user group leader can give to their members to join and it is also promoted on the meetup page. Then on the day of the presenter and user group leader call in to one of the team members who will stream it out to the .NET Foundation YouTube Event. 

This enables the organizers and presenters to focus in on their event and let the team handle the streaming logistics.


Additionally, while meetup.com is paid, the .NET Foundation has a pro account that any .NET user group can be part of and their meetup.com fees are covered.

**Comment by kulov** [comment]
Hi James,
One of the members of this Outreach group will stream the event to YouTube, is that correct?
In this case the outreach team will be very much responsible for the delivery of the event.
We would probably need to have playbook how this should be done - tools, steps, etc..

**Comment by jfbueno** [comment]
This is very nice. I was wondering, will this work with communities that don't speak English as their main language?

**Comment by jamesmontemagno** [comment]
@kulov that is the idea, we are actually looking at streamlining it with skype and a VM up in Azure. This way the host and presenter just call in and done.

@jfbueno Absolutely!

**Comment by stackedsax** [comment]
@jamesmontemagno Regarding "Skype and a VM up in Azure", are you talking about using a VM as an rtmp relay server to then send it on to YouTube?  For a small fee, I think paying for a service like restream.io would be simpler on this front.  Is there another approach you were considering?  Happy to take the technical conversation to another thread/issue if it makes sense to do that.

The earlier mention of OBS might be interesting if we wanted to introduce a more professional look to each broadcast.  We could throw on official logos and graphics that are displayed at the beginning and end of each segment.  But at that point, there would need to be an operator operating the controls so it wouldn't be as streamlined.  It may be something to aspire to later.

**Comment by jamesmontemagno** [comment]
@stackedsax it is somethign that @jongalloway and I are toying around with to make things super simple. The goal of using a VM is so that no one has to worry about setting up and configuring OBS, accounts, or anything like that. You just join a skype call and done. Inside of OBS it will be very simple, which is a single scene for the Skype throughput and we would actually use Restream as a single source to stream to YouTube events. 

The "producer" someone from the foundation would manage organizing the call and ensuring the stream and links are all setup and starts/stops the stream (we are looking at  ways of streamlining this in the future as well).

As for official logos and graphics I would encourage the presenter to share their screen and slide deck at the start and then give it a few minutes to start the presentation.

**Comment by kulov** [comment]
Can the event run in its native language? Or English language is preferred?

**Comment by jamesmontemagno** [comment]
However you would run your local user group is how you should do it :) We can mark the language in the title :)

**Comment by jamesmontemagno** [comment]
@jongalloway can you add on language in the template?

**Comment by kulov** [comment]
It might be a valid question from many others. Should we also add this in the Description?

**Comment by jamesmontemagno** [comment]
For sure :)

**Comment by techduggu** [comment]
Hi @jamesmontemagno / @jongalloway - I just came to know about this .NET Virtual UG support from .NET Foundation and I really liked it (was waiting for this support since we started switching our meetups to virtual).
I have a question - Is this supported only for the new and upcoming meetup sessions? I see we have a GitHub template to submit new UG session details. But if we want to associate/amplify our recent past meetup recordings to .NET Foundation's Virtual User Group playlist, Is there a way?
Also, the following link tagged under New issue template doesn't exist (was looking for streaming info required for live events):
https://github.com/dotnet-foundation/wg-outreach/issues/streaming-info.md

Thanks!

**Comment by jamesmontemagno** [comment]
Hmmm that is a great question.... we have just been adding them as people send them or are streamed directly to the YouTube channel, wouldn't see why not specifically, but just need to create a different template for that in Github. Will discuss with the WG

**Comment by shawnwildermuth** [comment]
This is complete.
