### ISSUE TITLE
Proposal acceptance review committee (PARC) protocol & criteria

### ISSUE THREAD

**Issue by jamiehowarth0** [dotnet-foundation/wg-outreach#13]
As per the last meeting, the Outreach group should focus on establishing a protocol for how proposal are accepted against a set of criteria that we need to establish.
I note that a couple of proposals have already been submitted in an established template, which is great to see, and I’ll be working on a number of proposals for UK outreach efforts as well.

I think it would be good to take some time to think about the various sorts of outreach activities the Foundation would be interested in providing financial support to, and then work out what an acceptable acceptance protocol looks like for each type of outreach activity, and ensure this is publicly documented so that applicants understand how their proposal is reviewed & how it is most likely to be successful.

I can immediately think of a couple of specific items, please feel free to add to this list:

- Semi-professional hackathons (I’m thinking GiveCamp/Humanitarian Toolbox -style events)
- K-12 outreach (I’m working with Code First: Girls – UK version of GirlDevelopIt – on two separate C# and Raspberry Pi syllabi, and I’ve previously mentored at Young Rewired State).

**Comment by rikgarner** [comment]
We should consider how we devise the application process to be low-friction and easy for non-native English speakers to use. Perhaps we consider use of multiple-choice questions as much as we can?

**Comment by naeemakram** [comment]
I am a test engineer and a published Udemy author, I know how to make tutorials(designing course outlines, simplifying concepts etc.), I'd love to help with any educational projects.

**Comment by rikgarner** [comment]
It's likely that we're going to get applications from people who want to kickstart a user-group in their locality. I _think_ that's probably a valid thing for us to do on a one-off basis - perhaps we should define up front what our expectations from an organizer are in those cases and what success measures we would use.

**Comment by chilberto** [comment]
@rikgarner - I agree that it is likely to have requests to start new groups and something I would encourage the group to support this. I also think it is valid for existing groups to be able to receive support.

What are measures for success then? Some ideas:
- member count
- attendance
- videos generated for .Net Community (http://live.dot.net)

I would like to see local user-groups contributing to the global .net community in some form. This of course ties in with some process to ensure high quality contributions.

**Comment by kulov** [comment]
I am totally in for supporting "just launched" user groups. They are in most need of financial support.
It might be a paid image stock service, tools and online services to get them going.
Of course we can qualify them by having them present 6 months meeting plan and/or list of speakers.
This would be small User group meetings on specific niche like Data Services/ASP.NET/AI for example.
Another cateory might be bootcamps/workshops/hackatons. There a venue needs to be booked for duration of two days and to be able to provide work place for delivering presentations and working on code. They would need catering too.
Another category could be events for non Microsoft stack developers. To get them introduced to the capabilities Microsoft technology with accent on Open Source/Inner Source.

**Comment by rikgarner** [comment]
I think we need to be careful that we don't put too many requirements on a group as it starts out. I was imagining a situation where a commited person might want to pop-up a group in their home town just to see if there was any interest; in this case I'd imagine they'd need a small injecton of money for pizza/snacks and/or to hire a room. We almost don't need to care about measuring if it's a success or not, just dropping the seed is the important thing. If it flies and the person comes back to us with an ask for some 'B-round' funds, then we can ask for some measurements

**Comment by rikgarner** [comment]
Just throwing a few ideas down for a simple questionnaire that we could have for applications for funding an event (concious that there will be many for whom English is not their first language, so wanted it to be easy to complete):

_What we need you to do:_
Book a venue
Devise the format (speakers, workshop, hackathon etc)
Find speakers and/or helpers
Do local publicity
Run the event
Let us know how it went


_What we can do:_
Provide funds for venue hire (one meeting)
Provide funds for catering (one meeting)
Give you a meetup account to promote your group (on-going)
Link you with mentors who can give you tips and advice (on-going)

_What we need to know to assess your application:_
What is your name?
How can we contact you?
What country/city/location?
What is the venue for the meeting?
When is it?
What will you be doing?
Who are you hoping will come?
