### ISSUE TITLE
[Virtual User Group Session] Building Island Tracker with Xamarin, Azure Functions, & Table Storage

### ISSUE THREAD

**Issue by jamesmontemagno** [dotnet-foundation/wg-outreach#14]
### Title
Building Island Tracker – Xamarin, Functions, Table Storage, and More

### Presenter Info
James Montemagno, Program Manager, Microsoft

### Technology
* Xamarin
* Azure Functions

###  User Group Association (if any)
* Name: Seattle Mobile .NET (Xamarin) User Group
* URL: https://www.meetup.com/SeattleMobileDevelopers/

### Date, Time, Time Zone
May 13th or June 3rd at 5PM Pacific

### Abstract

Join James as he walks through his latest creation, Island Tracker for Animal Crossing on iOS and Android. Built full cross-platform with Xamarin.Forms and leveraging Azure Functions and Table Storage as the cloud backend he will discuss his full architecture and demo how it all was pulled together. He will talk about lessons learned, preparing for release, continuous integration, user testing, and more! If you have ever wanted an insight into creating and deploying a cloud connected app then join in.

### Speaker Bio
James Montemagno is a Principal Program Manager for Client Developer Tools at Microsoft. He has been a .NET developer since 2005, working in a wide range of industries including game development, printer software, and web services. Prior to becoming a Principal Program Manager, James was a professional mobile developer and has now been crafting apps since 2011 with Xamarin. In his spare time, he is most likely cycling around Seattle or guzzling gallons of coffee at a local coffee shop. He can be found on Twitter @JamesMontemagno, blogs code regularly on his personal blog http://www.montemagno.com, and co-hosts the weekly development podcast Merge Conflict http://mergeconflict.fm.

**Comment by SaraJo** [comment]
James, this sounds like a great video to stream on You Tube. Would you be open to hosting it on the 3rd of June? Seems like a good way to test the new system which should, hopefully, be ready by then.

**Comment by jamesmontemagno** [comment]
https://www.meetup.com/SeattleMobileDevelopers/events/270882150/ has been created and we can setup the .NET Virtual User Group meet page and the youtube next.

**Comment by SaraJo** [comment]
Sounds great! Can I help with the latter two things?

**Comment by jamesmontemagno** [comment]
I have set this up (didn't see the comments sorry Sara!).

The Seattle Link: https://www.meetup.com/SeattleMobileDevelopers/events/270882150/

The .NET Virtual Link: https://www.meetup.com/dotnet-virtual-user-group/events/270931523/

They both point to an unlisted youtube for attendees that RSVPed to tune into. 

I also tried to standardize some verbage. 

On the Seattle group I put:
This session is part of the .NET Virtual User Group(https://www.meetup.com/dotnet-virtual-user-group) series, where you can join and find more virtual user groups happening around the world.

and on the .NET Virtual I put:
Kicking off our .NET Virtual User Group series is the Seattle Mobile .NET User Group (https://www.meetup.com/SeattleMobileDevelopers), which focuses on monthly user group meeting around Xamarin mobile development with .NET in Seattle & Redmond, WA.

**Comment by SaraJo** [comment]
This is great, thank you! Will definitely share the event.

**Comment by jongalloway** [comment]
Completed! Great success! Closing issue.
