### ISSUE TITLE
[Virtual User Group Session] What's New in C# 8 Interfaces (and how to use them effectively)

### ISSUE THREAD

**Issue by bsstahl** [dotnet-foundation/wg-outreach#15]
### Title
What's New in C# 8 Interfaces (and how to use them effectively)

### Presenter Info
Jeremy Clark

### Technology
* C# 8.0

### User Group Association

* Name: North West Valley .NET User Group
  URL: https://www.meetup.com/NWVDNUG/events/270203260/

* Name: Southeast Valley .NET User Group
  https://www.meetup.com/sevdnug/events/270203360/

### Date, Time, Time Zone
Wed June 24th at 6PM MST/PDT

### Abstract
C# 8 brings new features to interfaces, including default implementation, access modifiers, and static members. We'll look at these new features and see where they are useful and where they should be avoided. With some practical tips, "gotchas", and plenty of examples, we'll see how to use these features effectively in our code.

### Speaker Bio
Jeremy Clark makes developers better. By drawing on over 15 years of experience in application development, he helps developers take a step up in their skill set with a focus on making complex topics approachable regardless of skill level. He is a Microsoft MVP for .NET, and he has authored seven courses for Pluralsight, including "C# Interfaces", a course aimed at giving developers a clear understanding of abstraction. He loves speaking and has delivered over 300 technical presentations in the last 10 years in the United States and Europe. Jeremy lives in northern Washington with his lovely wife, 3 cats, 2 dogs, and a banjo.

**Comment by jongalloway** [comment]
+ @jamesmontemagno

**Comment by jamesmontemagno** [comment]
Do you already have a streaming platform, or do you need assistance there? 

If not then we can setup the event on the meetup page for promotion :)

**Comment by bsstahl** [comment]
We use Zoom for the meeting and stream using Justin James's Twitch channel https://www.twitch.tv/digitaldrummerj so I think we're ok as far as that goes.

**Comment by jongalloway** [comment]
It would be good to add the recording to the Virtual User Group playlist - you could either get us the recording from Twitch, or add it to your channel ({az}devs?) and we can add that to the playlist.

**Comment by bsstahl** [comment]
We have a few videos that Justin has on his YouTube feed. We don't have a specific YouTube channel yet. We could start one, or it could be hosted within a Foundation feed. Do you have a preference? We could get you videos, or YouTube links to videos either from Justin's or a User Groups feed, whatever works best.

**Comment by SaraJo** [comment]
This is great! Thank you for submitting this. Excited to have people using this platform. I'm travelling that week and not able to setup the Stream. @jongalloway  @jamesmontemagno are either of you free? If not I can ping the other directors. This seems like relevant content that people would love to see.

**Comment by jamesmontemagno** [comment]
@bsstahl if you can email me motz@microsoft.com the zoom link you want me to add in I will go ahead and get it setup. Since you don't need any additional setup with streaming, shouldn't be much else on our end. If you have a copy of the session you can email it over to me after and I can get it uploaded onto the .NET Foundation YouTube for archiving.

The only ask that we have is that you can add this blurb onto your meetup events:
This session is part of the .NET Virtual User Group(https://www.meetup.com/dotnet-virtual-user-group) series, where you can join and find more virtual user groups happening around the world.

And if you do announcements/intros could you share these 2 slides to help promote the group for others that may be interested in joining the Virtual Meetup group?
[Virtual User Group Slides.pptx](https://github.com/dotnet-foundation/wg-outreach/files/4781930/Virtual.User.Group.Slides.pptx)

**Comment by jamesmontemagno** [comment]
Event is live - https://www.meetup.com/dotnet-virtual-user-group/events/271319047

**Comment by jamesmontemagno** [comment]
The only ask that we have is that you can add this blurb onto your meetup events:
This session is part of the .NET Virtual User Group(https://www.meetup.com/dotnet-virtual-user-group) series, where you can join and find more virtual user groups happening around the world.

And if you do announcements/intros could you share these 2 slides to help promote the group for others that may be interested in joining the Virtual Meetup group? https://github.com/dotnet-foundation/wg-outreach/files/4781930/Virtual.User.Group.Slides.pptx
