### ISSUE TITLE
[Virtual User Group Session] Building a CoViD Patient Scanning App in 24 Hours with Xamarin

### ISSUE THREAD

**Issue by AuriR** [dotnet-foundation/wg-outreach#17]
### Title
Building a CoViD Patient Scanning App in 24 Hours with Xamarin

###  User Group Association (if any)
* Name: Indy Xamarin Meetup
* URL: https://www.meetup.com/Indy-Xamarin/

### Streaming Support
[ ] Live streaming to the .NET Foundation YouTube channel (if you tell us how to set it up... our meeting was going to be in Teams for great recording)

Fill in [x] or leave [ ] if not needed.

> If not checked, we will:
> 1. Promote your event to the Virtual Meetup members.
> 2. If you post your session video to YouTube, we'll add it to the .NET Foundation Virtual Event playlist.

> If checked, we will:
> 1. Provide you a live streaming link to provide to your meetup members.
> 2. Live stream your event to the .NET Foundation YouTube channel ([more information here](streaming-info.md)). 
> 3. When complete, your event video will be added to the .NET Foundation Virtual Event playlist.

### Date, Time, Time Zone
Wednesday, June 24, 2020 6:30 PM Eastern

### Presenter Info
Auri Rahimzadeh, Owner, Auri's Ideas

### Technology
* Xamarin
* Xamarin.Essentials
* Azure Storage
* Barcode Scanning

### Abstract

A walkthrough of an app I recently wrote for scanning CoViD patients in my city. They needed a way to marry a patient and kit without manual data entry, and they needed it in 24 hours for the free CoViD tests starting that week. I'll explain the requirements gathering process, the initial designs, the Xamarin mobile application, how we mostly avoided back-end development, and how usage analytics and the first week panned out.

### Speaker Bio
Auri Rahimzadeh is an accomplished software engineer, technology writer and book author. He has written three books: Hacking the PSP, Geek My Ride, and co-authored Hacking Digital Cameras, and tech edited various programming works. Rahimzadeh has contributed to many digital entertainment technology standards, including HDTV and DVD. Having taught side by side with Steve Wozniak, co-founder of Apple, Auri continues to share a passion for technology education. Currently Mr. Rahimzadeh is owner of Auri’s Ideas, a Fishers, Indiana based software development firm.

**Comment by jongalloway** [comment]
@AuriR Just double checking - you didn't check the box for live streaming support, so you've got that covered?

**Comment by AuriR** [comment]
We’re just using Microsoft Teams, and will upload to YouTube afterwards. Does that work, or is YouTube better? I’ve never done live streaming with YouTube, so let me know 😊

Thanks and Best,

-Auri

--
Never confuse motion with action.
www.auri.net<http://www.auri.net> / @Auri on Twitter

**Comment by jamesmontemagno** [comment]
That works. If you want the .NET Foundation to host the recording just send over the recording to us and we will upload. Else just a link to your YouTube recording so we can add to the playlist.

Can you send me an email (motz@microsoft.com) with the link for the online event and I will get it setup.

**Comment by AuriR** [comment]
Got it, thanks!

Meetup event: https://www.meetup.com/Indy-Xamarin/events/271307694/

Once they RSVP they’ll get the event link.

Please let me know if you have any questions!

Thanks and Best,

-Auri

--
Never confuse motion with action.
www.auri.net<http://www.auri.net> / @Auri on Twitter

**Comment by jamesmontemagno** [comment]
Sorry, can you email the live stream event so I can add it to the RSVP event.

**Comment by AuriR** [comment]
Here ya go, for the CoViD App event: https://teams.microsoft.com/l/meetup-join/19%3ameeting_MDVkZmNjOGQtMDNiNy00ZmYzLTk2MmQtNzRiMDBlMGI3Zjli%40thread.v2/0?context=%7b%22Tid%22%3a%225c8085d9-1e88-4bb6-b5bd-e6e6d5b5babd%22%2c%22Oid%22%3a%220209d9cb-e49d-4f3a-8802-dbb99b6cf915%22%7d

--
Never confuse motion with action.
www.auri.net<http://www.auri.net> / @Auri on Twitter

**Comment by jamesmontemagno** [comment]
Posted - https://www.meetup.com/dotnet-virtual-user-group/events/271483421/

**Comment by AuriR** [comment]
Thanks!

--
Never confuse motion with action.
www.auri.net<http://www.auri.net> / @Auri on Twitter

**Comment by jamesmontemagno** [comment]
The only ask that we have is that you can add this blurb onto your meetup events:
This session is part of the .NET Virtual User Group(https://www.meetup.com/dotnet-virtual-user-group) series, where you can join and find more virtual user groups happening around the world.

And if you do announcements/intros could you share these 2 slides to help promote the group for others that may be interested in joining the Virtual Meetup group? https://github.com/dotnet-foundation/wg-outreach/files/4781930/Virtual.User.Group.Slides.pptx

**Comment by AuriR** [comment]
Will do – I’ll get those downloaded.

And here’s a link to the video of tonight’s session:

https://youtu.be/uVXQ8VEfYV4

Thanks and Best,

-Auri

--
Never confuse motion with action.
www.auri.net<http://www.auri.net> / @Auri on Twitter

**Comment by SaraJo** [comment]
Amazing, thank you for sharing this. Any open items currently or can this issue be closed? @AuriR @jamesmontemagno

**Comment by jamesmontemagno** [comment]
All good! will add it to the playlist :)

**Comment by AuriR** [comment]
Thanks!

--
Never confuse motion with action.
www.auri.net<http://www.auri.net> / @Auri on Twitter


________________________________
