### ISSUE TITLE
[Virtual User Group Session] Blazor - The Next Big Thing

### ISSUE THREAD

**Issue by AuriR** [dotnet-foundation/wg-outreach#18]
### Title
Blazor - The Next Big Thing

###  User Group Association (if any)
* Name: Indy .NET Consortium
* URL: https://www.meetup.com/Indy-NET-Consortium/

### Streaming Support
- [ ] Live streaming to the .NET Foundation YouTube channel

Fill in [x] or leave [ ] if not needed.

> If not checked, we will:
> 1. Promote your event to the Virtual Meetup members.
> 2. If you post your session video to YouTube, we'll add it to the .NET Foundation Virtual Event playlist.

> If checked, we will:
> 1. Provide you a live streaming link to provide to your meetup members.
> 2. Live stream your event to the .NET Foundation YouTube channel ([more information here](streaming-info.md)). 
> 3. When complete, your event video will be added to the .NET Foundation Virtual Event playlist.

### Date, Time, Time Zone
July 1, 2020 6:30 PM Eastern

### Presenter Info
Name, Nick George, Senior Consultant, Valorem Reply

### Technology
* Blazor
* SignalR
* .NET Core

### Abstract

Nick takes us for an adventure with .NET Blazor and why it's the next big thing and how you should start learning about it now to prepare yourself for the future of application development.

### Speaker Bio

Nick George is looking to make a difference in this world, one commit at a time. He has been a developer for 20 years, with his first piece of code being written in 3rd grade for a fan website of the real-time strategy game StarCraft. He loves to get out outdoors to bike, hike, and run, as well as weight lift and stay active. He works for Valorem Reply, a software consulting company, out of Kansas City, where he's able to focus on helping businesses transition to the cloud, create custom software, and mentor developers to honing their craft and becoming experts in the field.

**Comment by jamesmontemagno** [comment]
Can you send me an email (motz@microsoft.com) with the link for the online event and I will get it setup.

**Comment by AuriR** [comment]
Meetup event: https://www.meetup.com/Indy-NET-Consortium/events/271307609/<https://www.meetup.com/Indy-Xamarin/events/271307694/>

Once they RSVP they’ll get the event link.

Please let me know if you have any questions!

Thanks and Best,

-Auri


--
Never confuse motion with action.
www.auri.net<http://www.auri.net> / @Auri on Twitter

**Comment by jamesmontemagno** [comment]
Sorry, can you email the live stream event so I can add it to the RSVP event.

**Comment by AuriR** [comment]
Here ya go, for the Blazor event: https://teams.microsoft.com/l/meetup-join/19%3ameeting_Y2JlMDRkNTQtYzQ5Ni00MTBkLTllMGMtN2I0YjhkM2FjYWY5%40thread.v2/0?context=%7b%22Tid%22%3a%225c8085d9-1e88-4bb6-b5bd-e6e6d5b5babd%22%2c%22Oid%22%3a%220209d9cb-e49d-4f3a-8802-dbb99b6cf915%22%7d


--
Never confuse motion with action.
www.auri.net<http://www.auri.net> / @Auri on Twitter


________________________________

**Comment by jamesmontemagno** [comment]
Posted - https://www.meetup.com/dotnet-virtual-user-group/events/271483491/?isFirstPublish=true

**Comment by AuriR** [comment]
Thanks!

--
Never confuse motion with action.
www.auri.net<http://www.auri.net> / @Auri on Twitter


________________________________

**Comment by jamesmontemagno** [comment]
The only ask that we have is that you can add this blurb onto your meetup events:
This session is part of the .NET Virtual User Group(https://www.meetup.com/dotnet-virtual-user-group) series, where you can join and find more virtual user groups happening around the world.

And if you do announcements/intros could you share these 2 slides to help promote the group for others that may be interested in joining the Virtual Meetup group? https://github.com/dotnet-foundation/wg-outreach/files/4781930/Virtual.User.Group.Slides.pptx

**Comment by AuriR** [comment]
Will do!!

--
Never confuse motion with action.
www.auri.net<http://www.auri.net> / @Auri on Twitter
