### ISSUE TITLE
[XAFers Arizona User Group] XAFers Community Standup. (Best Practices)

### ISSUE THREAD

**Issue by jjcolumb** [dotnet-foundation/wg-outreach#19]
### Title
XAFers Community Standup. (Best Practices)

###  User Group Association (if any)
* Name: XAFers Community Standup. (Best Practices)
* URL: https://www.meetup.com/Arizona-XAFers-User-Group

### Streaming Support
- [ ] Live streaming to the .NET Foundation YouTube channel

Fill in [x] or leave [ ] if not needed.

> If not checked, we will:
> 1. Promote your event to the Virtual Meetup members.
> 2. If you post your session video to YouTube, we'll add it to the .NET Foundation Virtual Event playlist.

> If checked, we will:
> 1. Provide you a live streaming link to provide to your meetup members.
> 2. Live stream your event to the .NET Foundation YouTube channel ([more information here](streaming-info.md)). 
> 3. When complete, your event video will be added to the .NET Foundation Virtual Event playlist.

### Date, Time, Time Zone
Thursday, July 9, 2020 10:00 AM Arizona Time

### Presenter Info
Jose Javier Columbie (Organizer)
Joche Ojeda (DevExpress MVP)
Manuel Grundner (DevExpress MVP)
Dave Hesketh (DevExpress MVP)

### Technology
* .NET Core
* .NET Framework
* DevExpress ExpressApp Framework

### Abstract

Interested in building Windows and Web apps with C# and a single code base.
Let's talk. I started this group to meet and help others developer using DevExpress Express App Framework. All skill levels are welcome, we will cover topics from getting started to really complex and advanced scenarios. This session will cover XAF Best Practices. See you inside!

### Speaker Bio
Jose Javier Columbie (Organizer)
Joche Ojeda (DevExpress MVP)
Manuel Grundner (DevExpress MVP)
Dave Hesketh (DevExpress MVP)

**Comment by jamesmontemagno** [comment]
Can you send me an email (motz@microsoft.com) with the link for the online event and I will get it setup.

**Comment by jamesmontemagno** [comment]
Live now on  - https://www.meetup.com/dotnet-virtual-user-group/events/271418524/

**Comment by SaraJo** [comment]
Thank you, @jamesmontemagno and @jjcolumb. Closing the issue as it has been posted.
