### ISSUE TITLE
Schema Modeling for Cosmos: Yes, it matters!

### ISSUE THREAD

**Issue by bsstahl** [dotnet-foundation/wg-outreach#20]
### Title
Schema Modeling for Cosmos: Yes, it matters!

###  User Group Association
* Name: Southeast Valley .NET User Group
  https://www.meetup.com/sevdnug/events/271474016/

* Name: North West Valley .NET User Group
  URL: https://www.meetup.com/NWVDNUG/events/271465259/

### Streaming Support
- [ ] Live streaming to the .NET Foundation YouTube channel

Fill in [x] or leave [ ] if not needed.

> If not checked, we will:
> 1. Promote your event to the Virtual Meetup members.
> 2. If you post your session video to YouTube, we'll add it to the .NET Foundation Virtual Event playlist.

> If checked, we will:
> 1. Provide you a live streaming link to provide to your meetup members.
> 2. Live stream your event to the .NET Foundation YouTube channel ([more information here](streaming-info.md)). 
> 3. When complete, your event video will be added to the .NET Foundation Virtual Event playlist.

### Date, Time, Time Zone
Thursday, July 23, 2020 at 6pm MST/PDT

### Presenter Info
Nuri Halperin

### Technology
* CosmosDB
* Document Oriented Design

### Abstract
Document oriented databases are deceivingly easy to use. Just shove some stuff in and it works? Well, not so fast…

Turns out, just because you have no schema or no enforced document structure doesn’t mean that anything goes. How you structure your document will have an impact on your cost, your speed, and your ability to use the database. Sharing from Nuri’s experience using Cosmos and Mongo, this talk will review some common patterns and anti-patterns in document oriented design. Nuri will show you some common scenarios and how to approach designing them appropriately for this brave new world.

### Speaker Bio
Nuri Halperin helps companies get software done! He architects and builds scalable websites and business applications. His experience of over 2 decades ranges from founding CTO of Jdate.com to international e-commerce multilingual websites, to social photo sharing. His focus is on helping companies move to the Azure and creating cloud native solutions.

Nuri is a Microsoft MVP, a MongoDB Master, and author of instructional online courses on Pluralsight.com. He also appeared on MSDN Channel 9 and podcasts. He is involved in the software community, coaches youth robotics, and contributes to OSS projects.

**Comment by jongalloway** [comment]
I'm setting that up here: https://www.meetup.com/dotnet-virtual-user-group/events/271613361/

Contacted you via e-mail for stream URL.
