### ISSUE TITLE
[Virtual User Group Session] Level up on Functional Programming by rebuilding LINQ

### ISSUE THREAD

**Issue by bsstahl** [dotnet-foundation/wg-outreach#21]
### Title
Level up on Functional Programming by rebuilding LINQ

###  User Group Association (if any)
* Name: North West Valley .NET User Group
  URL: https://www.meetup.com/NWVDNUG/events/271465259/

* Name: Southeast Valley .NET User Group
  https://www.meetup.com/sevdnug/events/271474016/

### Streaming Support
- [ ] Live streaming to the .NET Foundation YouTube channel

Fill in [x] or leave [ ] if not needed.

> If not checked, we will:
> 1. Promote your event to the Virtual Meetup members.
> 2. If you post your session video to YouTube, we'll add it to the .NET Foundation Virtual Event playlist.

> If checked, we will:
> 1. Provide you a live streaming link to provide to your meetup members.
> 2. Live stream your event to the .NET Foundation YouTube channel ([more information here](streaming-info.md)). 
> 3. When complete, your event video will be added to the .NET Foundation Virtual Event playlist.

### Date, Time, Time Zone
Wednesday, August 26, 2020 6:00 PM MST/PDT

### Presenter Info
Cameron Presley, Lead Software Engineer, SentryOne

### Technology
* Functional Programming
* C#
* LINQ
* Map, Filter, Reduce

### Abstract

When taking your first steps into functional programming, you'll quickly run into blog posts talking about how to simplify complex loops by using the trinity of list operations: map, filter, and reduce. But what are these methods actually doing under the hood to help simplify your code?

If you're familiar with the .NET landscape, then you already have experience with an implementation of the trinity within LINQ (Language Integrated Query). However, what if I told you that by learning how LINQ implements map (Select), filter (Where), and reduce (Aggregate), you actually know how other languages implement the same constructs?

Intended for C# developers who have some experience with LINQ and an interest in learning functional programming, by the end of this session, you will have learned how to work with the Func type, generics, and extension methods!

### Speaker Bio

Cameron Presley is a Lead Software Engineer for SentryOne (https://www.sentryone.com), a speaker, a Microsoft MVP, Director of Speaker Relations for CodeStock (@CodeStock) and co-organizer of FunctionalKnox (@FunctionalKnox).

Based out of Charlotte, North Carolina, Cameron has ten years of experience working with start-ups and large enterprise both publicly and privately held to architect solutions, implement solutions, and training developers to be better today than what they were yesterday!

In his spare time, Cameron can be found hanging out with his family, playing board games, jamming on the bass guitar, and reading books.

### Language (if not English)
en-us

**Comment by jongalloway** [comment]
Posted
