### ISSUE TITLE
[Virtual User Group Session] XHackers Xamarin Meetup Aug 2020 - Adaptive UI & FreshMvvm Practices

### ISSUE THREAD

**Issue by techduggu** [dotnet-foundation/wg-outreach#25]
### Title
[Online] XHackers Xamarin Meetup Aug 2020 - Adaptive UI & FreshMvvm Practices

###  User Group Association (if any)
* Name: XHackers - .Net Mobile Developers User Group - Bangalore, India
* URL: https://www.meetup.com/XHackers/

### Streaming Support
- [ ] Live streaming to the .NET Foundation YouTube channel

Fill in [x] or leave [ ] if not needed.

> If not checked, we will:
> 1. Promote your event to the Virtual Meetup members.
> 2. If you post your session video to YouTube, we'll add it to the .NET Foundation Virtual Event playlist.

> If checked, we will:
> 1. Provide you a live streaming link to provide to your meetup members.
> 2. Live stream your event to the .NET Foundation YouTube channel ([more information here](streaming-info.md)). 
> 3. When complete, your event video will be added to the .NET Foundation Virtual Event playlist.

### Date, Time, Time Zone
August 1st at 11:00 AM India Standard Time

### Presenter Info
1. Aneesh Jha, Software Developer, K-Mart India (KAS)
2. Chandan Pradeep, Mobile Developer, K-Mart India (KAS)

### Technology
* Xamarin
* Xamarin.Forms
* FreshMvvm

### Abstract

Session-1: **Flex and Bindable layouts for Adaptive UI** - Aneesh Jha
Xamarin.Forms Flex-layout with Bindable layout to achieve a custom collection view and wrap UI as per the screen dimensions. We will also discuss on Control template with Bindings that helps to generate reusable common UI or custom templates across the entire app architecture.

Session-2: **FreshMvvm best practices for enterprise applications** - Chandan Pradeep
FreshMvvm for Xamarin.Forms, Dependency Injection using TinyIOC, Auto wiring of Page with its Page Models, use of Converters efficiently, and view caching with auto navigation to last viewed page.

### Speaker Bio
1. Aneesh Jha: Software Developer at K-Mart India (KAS) with 3.6 years of experience. Currently, working on cross-platform and native mobile app technologies (Xamarin.iOS). You can find him on https://www.linkedin.com/in/aneesh-jha-464668bb/

2. Chandan Pradeep: Mobile Developer at K-Mart India (KAS) with more than 5 years of experience in building cross-platform apps using Xamarin. Skilled in Hybrid Mobile App development usually through Xamarin and React Native. He also has hands-on experience in building native Android and iOS applications. You can find him on https://www.linkedin.com/in/chandan-pradeep-a5676b66/

**Comment by jongalloway** [comment]
Thanks for submitting this, @techduggu! We've got an updated process to move away from GitHub issues, but it wasn't super obvious. We'll update to fix that.

The new process is to submit using [this form](https://bit.ly/2OohRR2) (includes the same info).

It would be really helpful if you can do that so we can test out from an organizer perspective and make sure it works for you. Please let us know if you hit any problems.

**Comment by techduggu** [comment]
Thanks @jongalloway for creating a form-based approach. I have submitted the event details. 
By the way, I have again noticed that streaming-info.md link (given on the form) is leading to not found page which I had also reported here: https://github.com/dotnet-foundation/wg-outreach/issues/12#issuecomment-653919106
