### ISSUE TITLE
[XAFers Arizona User Group] XAFers Community Standup. Testing, DevOps and more.

### ISSUE THREAD

**Issue by jjcolumb** [dotnet-foundation/wg-outreach#28]
### Title
XAFers Community Standup. Testing, DevOps and more.

###  User Group Association (if any)
* Name: XAFers Arizona User Group
* URL: https://www.meetup.com/Arizona-XAFers-User-Group

### Streaming Support
- [ ] Live streaming to the .NET Foundation YouTube channel

Fill in [x] or leave [ ] if not needed.

> If not checked, we will:
> 1. Promote your event to the Virtual Meetup members.
> 2. If you post your session video to YouTube, we'll add it to the .NET Foundation Virtual Event playlist.

> If checked, we will:
> 1. Provide you a live streaming link to provide to your meetup members.
> 2. Live stream your event to the .NET Foundation YouTube channel ([more information here](streaming-info.md)). 
> 3. When complete, your event video will be added to the .NET Foundation Virtual Event playlist.

### Date, Time, Time Zone
Thursday, August 13, 2020 10:00 AM Arizona Time

### Presenter Info
Jose Javier Columbie (Organizer)
Joche Ojeda (DevExpress MVP)
Manuel Grundner (DevExpress MVP)
Dave Hesketh (DevExpress MVP)

### Technology
* .NET Core
* .NET Framework
* DevExpress ExpressApp Framework

### Abstract
Interested in building Windows and Web apps with C# and a single code base.
Let's talk. I started this group to meet and help others developer using DevExpress Express App Framework. All skill levels are welcome, we will cover topics from getting started to really complex and advanced scenarios. This session will cover XAF Best Practices focused on Testing and DevOps. See you inside!

### Speaker Bio
Jose Javier Columbie (Organizer)
Joche Ojeda (DevExpress MVP)
Manuel Grundner (DevExpress MVP)
Dave Hesketh (DevExpress MVP)

**Comment by jongalloway** [comment]
Thanks for submitting this, @jjcolumb! We've got an updated process to move away from GitHub issues, but it wasn't super obvious. We'll update to fix that.

The [new process](https://github.com/dotnet-foundation/wg-outreach#virtual-meetups) is to submit using [this form](https://bit.ly/2OohRR2) (includes the same info). 

It would be really helpful if you can do that so we can test out from an organizer perspective and make sure it works for you. Please let us know if you hit any problems.

**Comment by jjcolumb** [comment]
Hello @jongalloway. I just submitted the form. Thanks

**Comment by jongalloway** [comment]
Got your form submission, so I'm closing this issue. Thanks!
