### ISSUE TITLE
.NET Virtual User Group - Website Integration

### ISSUE THREAD

**Issue by jamesmontemagno** [dotnet-foundation/wg-outreach#29]
Now that the .NET Virtual User Group is off the ground running, I recommend that we make it easy for developers & user group leaders to find out about the .NET Virtual User Group and get involved.

I propose that a new page on the .NET Foundation website (/virtual-user-group) is created that has the following:

* Describes what the .NET Virtual User group is for the community
* How organizers can use it to promote existing online meetups
* How the .NET Foundation can help user groups go online via the .NET Foundation YouTube.
* List the next 5 upcoming events
* Link to past events with the YouTube playlist

**Comment by clairernovotny** [comment]
Love it. To keep the information hierarchy consistent, I think the page should live under https://github.com/dotnet-foundation/website/tree/master/input/community. If we want a shorter URL for making it easier, we can do that in the route.json: https://github.com/dotnet-foundation/website/blob/master/input/routes.json.

**Comment by jamesmontemagno** [comment]
Initial PR - https://github.com/dotnet-foundation/website/pull/272

**Comment by jamesmontemagno** [comment]
Closing now :) it is live!!! https://dotnetfoundation.org/community/meetups and https://dotnetfoundation.org/community/virtual-user-group
