### ISSUE TITLE
Official .NET Foundation Meetups

### ISSUE THREAD

**Issue by jamesmontemagno** [dotnet-foundation/wg-outreach#32]
The recently launched [.NET Virtual User Group](https://dotnetfoundation.org/community/virtual-user-group) enables any existing .NET user group to go online by requesting stream support and also helps promote existing user group's online events. This is a great first step, but there is a great opportunity to now host "official" .NET Foundation meetups!

## Proposal - Official Meetups
The proposal is to extend the existing working group for the .NET Virtual User Group to not only promote existing user groups, but also to create an ongoing meetup series. A goal would be to have a Monthly/Bi-weekly/Weekly meetup streamed to the .NET Foundation YouTube and promoted on the .NET Virtual User Group meetup page. 

The user group could start with .NET Foundation news & updates (and maybe general .NET news). Then could feature .NET Foundation project leads to have them talk about and demo their project. This is a great way to promote existing projects, get others interested in the .NET Foundation, and get more people contributing to .NET projects.

## What is needed
The technical requirements are all in place with YouTube & StreamYard that is already used to help existing user groups go online. So, the new flow is having a ".NET Virtual User Group" leader that organizes and setups and runs the events. If we decide to do this we just need to decide when the events are happening and start them up.

**Comment by shawnwildermuth** [comment]
Can you elaborate now the Virtual Meetups do not already facilitate this?
