### ISSUE TITLE
Future of .NET User Groups

### ISSUE THREAD

**Issue by kulov** [dotnet-foundation/wg-outreach#33]
As these days joining a .NET Group miles away from you is just one click away, I am trying to imagine how these UGs will evolve in future.
Obviously the ones with the biggest audiences will sustain as they will be able to attract top rank speakers, even directly from the PGs.
This will eventually make smaller UGs to sunset as there will be handfull of events each month for you to watch on any topic you would like.
Or they might actually specialize in particular topic and grow their audience and knowledge in that particular topic only.
Generalist group might be a very unlikely one to see in future.

Any thoughs?

**Comment by shawnwildermuth** [comment]
We've created the speaker's bureau that I think will help. I am closing this unless there is something else to do.
