### ISSUE TITLE
.NET Speaker Directory Proposal  

### ISSUE THREAD

**Issue by JaySing** [dotnet-foundation/wg-outreach#34]
## Description: 

The .NET community would benefit from a collective list of all the .NET speakers around the world that is publicly accessible, up-to-date, and easy to contribute to. It would be an opportunity for collaboration amongst the community to build a public list of .NET speakers around the world. The purpose of this speaker list (aka "Speaker Directory") would be to serve the community by bringing awareness to .NET speaker availability and scheduling of global .NET events. 

This proposal is backed by internal MS and external community interest. I surveyed Microsoft MVP and .NET community members to find out their interest and need for a speaker directory and found the following:  

* Out of 125+ people surveyed 123 people were speakers; 89 were Event Organizers. 
* 85% said finding/scheduling speakers was below average.  
* 15% said they were not in need of this directory. 

<center>
<img width="692" alt="Screen Shot 2020-09-01 at 15 45 40" src="https://user-images.githubusercontent.com/8364831/91898800-4534d400-ec6a-11ea-9438-05faab20560e.png">
<br>
<br>
<img width="586" alt="Screen Shot 2020-09-01 at 15 45 24" src="https://user-images.githubusercontent.com/8364831/91898817-4fef6900-ec6a-11ea-86ac-8c75457917c2.png">
</center>
 

## Proposal 

I have been working with David Glick, Maxime Rouiller, and Julie Lerman to discuss implementation details and David has a working prototype that can be seen at https://dnf-speaker-directory-test.netlify.app/community/speakers/ 

Hosted on the .NET Foundation site and modeled after cloud advocates [website]( https://developer.microsoft.com/en-us/advocates/), which uses [yaml]( https://github.com/MicrosoftDocs/cloud-developer-advocates) to display and update information. This can be adapted to use Statiq, which the .NET Foundation already uses, and add filtering based on location and topics. There should not be any budget required on top of the committee. 

## Size of Committee Requested/Budget 

3 Volunteers: 

* Project Manager: Jayme Singleton 
* Site Development: David Glick / Maxime Rouiller 
* PR Review & Approval: .NET Foundation member / Maxime Rouiller 

## Which Goal and Priority is this project aligned with: 

* Build awareness of the vast pool of .NET Speakers around the world.  
* Amplify speaker engagements and opportunities.  
* Encourage more individuals to present on .NET and related tools/products.  
* Engage user groups and community members during these times and beyond. 
* Opening speaker opportunities to present to a global audience. 
* Promote local, global, in-person, and online events. 

## Success Metrics

From the number of individuals that add their information as a speaker to the collective list of speakers. As well as the number of scheduled speakers as a result of using this platform. If the platform is highly active, utilized, and shared/promoted.

**Comment by bjablonsky** [comment]
This is awesome! 

I'm the co-organizer of the NYC .NET Devs User Group, and I've been slowly collecting a speakers list including potential speakers to reach out to. I had the idea of creating a .NET User Group info hub earlier this year. This would include a list of speakers willing to talk about .NET-related talks (and their travel availability), speaking opportunities (both user group and related conferences), and resources (such as sponsors, partner events, etc) for the user groups. 

Is the scope of this project limited to just speakers, or can it be expanded to encompass more features such as speaking opportunities and user group resources?

**Comment by bsivanov** [comment]
It seems this is done now? The [readme](https://github.com/dotnet-foundation/wg-outreach#speaker-directory) should also be updated.

**Comment by shawnwildermuth** [comment]
Still need to link to the main page before we close this.

**Comment by shawnwildermuth** [comment]
This should be complete now.
