### ISSUE TITLE
Link for .NET Foundation virtual meetups present in README.md is not working

### ISSUE THREAD

**Issue by AshirwadSatapathi** [dotnet-foundation/wg-outreach#36]
The link to know more about the Virtual Meetups at Net Foundation Virtual Meetups is not working. It's under current initiative's, Virtual Meetup section.

**Comment by DaveNoderer59** [comment]
Link should be /virtual_meetup not /virtual-user-group

**Comment by shawnwildermuth** [comment]
Is this complete or do you need help to close this issue?

**Comment by AshirwadSatapathi** [comment]
Yes, It is resolved. Closing  it.
