### ISSUE TITLE
Support the C# Community on Discord

### ISSUE THREAD

**Issue by jrusbatch** [dotnet-foundation/wg-outreach#42]
## Description:
The C# Discord community developed and maintains an open-source, community-built, Azure-hosted bot for moderation tasks and to provide an interactive C# REPL experience for our users. Over the past year our community has grown from ~8k members to ~22k members, and the basic Azure tier is no longer sufficient for our needs. We are looking for assistance from the .NET Foundation to help with hosting costs, and - if possible - to provide an organization account so that the hosting is owned by the administrators of our community as a group.
 
## Measure of impact:
>22k Developers

## Requested Budget:
~250/mo.

**Comment by shawnwildermuth** [comment]
Are you registered as a non-profit? (e.g. 503c)?

**Comment by jrusbatch** [comment]
@shawnwildermuth We're not.

cc: @tannergooding @Cisien

**Comment by shawnwildermuth** [comment]
Feel free to join us at 3pm ET if you can:  

[Monthly Outreach Working Group Meeting](https://teams.microsoft.com/l/meetup-join/19%3ameeting_MGQ0NDEwY2MtZTJhMC00OTIzLWFmNTQtZGVkZGQyODk5Zjc2%40thread.v2/0?context=%7b%22Tid%22%3a%2216076fdc-fcc1-4a15-b1ca-32c9a255900e%22%2c%22Oid%22%3a%22d40b2907-58b0-4a8e-abc4-3c2fc4641d24%22%7d)

**Comment by Cisien** [comment]
After looking at the invoice for may, the current cost is roughly $333

The breakdown is:
PGSQL: 133.27 (General Purpose, 2 vCore(s), 100 GB)
AKS: 200.80 (4 Standard_B2s nodes, OS disks, and related costs)

**Comment by shawnwildermuth** [comment]
Per month?

**Comment by Cisien** [comment]
Yes

**Comment by Cisien** [comment]
@shawnwildermuth any update on this?

**Comment by shawnwildermuth** [comment]
This is in the processing of happening. We'll have something to announce very soon.

**Comment by Cisien** [comment]
We're all set! Thanks!

**Comment by NicoleAbuhakmeh** [comment]
FYI - we'll be featuring this in the upcoming newsletter for August.

**Comment by tannergooding** [comment]
@NicoleAbuhakmeh, Do you need anything from us such a small blurb or link beyond what https://dotnet.microsoft.com/platform/community already has?

**Comment by jrusbatch** [comment]
@NicoleAbuhakmeh That's awesome! Like @tannergooding said, let us know if we can help out in any way!

**Comment by NicoleAbuhakmeh** [comment]
> @NicoleAbuhakmeh, Do you need anything from us such a small blurb or link beyond what https://dotnet.microsoft.com/platform/community already has?

That would be awesome!  You can drop it here or submit it here: [https://forms.office.com/r/8hAv7S659s](https://forms.office.com/r/8hAv7S659s)

**Comment by RubyNova** [comment]
Hi there @NicoleAbuhakmeh - this has just been brought to my attention. As the owner of the platform in question, I've told the others I'm more than happy to write something up and run some drafts by them a few times before submitting this via your submission link.

When is the date you would like this by at the latest? :)
