### ISSUE TITLE
Sign up to be part of the committee 404's for anyone not part of the team.

### ISSUE THREAD

**Issue by wordshaker** [dotnet-foundation/wg-outreach#44]
## Problem

In the README, the section for `Joining the Committee & Meetings` has a link to the GitHub discussions page. This is only visible to team members of this repository and otherwise shows a 404.

This could be a blocker for some people wanting to take part in this committee

## Screenshot of the section in README

![image](https://user-images.githubusercontent.com/13496774/123686145-6133e280-d847-11eb-8d1e-fb29c13afd39.png)

**Comment by jamesmontemagno** [comment]
Can you try to go to -> https://github.com/orgs/dotnet-foundation/teams/outreach/members and there should be a button on the top right to request to join @wordshaker

**Comment by shawnwildermuth** [comment]
We've changed the link, sorry this too so long.

**Comment by wordshaker** [comment]
Thanks both!
