### ISSUE TITLE
Collect analytics on the reach of .NET Foundation sponsored Meetups

### ISSUE THREAD

**Issue by danroth27** [dotnet-foundation/wg-outreach#45]

**Comment by danroth27** [comment]
I think the original idea was to get a measure of the impact of the .NET Foundation's efforts to support .NET Meetups so that we had a better idea of how much .NET related outreach we are supporting.

**Comment by jamesmontemagno** [comment]
Yes, we have these metrics and can deeper engage and @jongalloway  and I are working with the outreach team on some new things here.

**Comment by codehippie1** [comment]
This one Relates to issue 50 - https://github.com/dotnet-foundation/wg-outreach/issues/50

**Comment by codehippie1** [comment]
@jamesmontemagno Is it possible to download meetup pro analytics data? Or do they only allow to view analytics on their website(I don't have access to the account)

**Comment by jamesmontemagno** [comment]
Some quick stats:
* 381 Groups
* 130 Groups last meeting was in 2022 (most active schedule)
* 91 Groups last meeting was in 2021 (17 active schedule)
* 72 Groups last meeting was in 2020 (1 group active schedule)
* 45 Groups last meeting was in 2019 (1 group active schedule)
* 31 Groups last met in 2018/17/16 
*  12 Groups have never met & no scheduled 3events (most were formed in 2018/19/20)

**Comment by DaveNoderer59** [comment]
Yeah, things have changed. We did delete 21 that had never met at one point.  Good to find ways to engage the user group leaders.

**Comment by jamesmontemagno** [comment]
We now have access to this, we have started a quarterly call, and we will start reporting quarterly on user groups that are running through meetup pro account.

**Comment by shawnwildermuth** [comment]
I think this is now in the hands of the committee.
