### ISSUE TITLE
User Group Sub-Committee

### ISSUE THREAD

**Issue by jamesmontemagno** [dotnet-foundation/wg-outreach#50]
## Title: 
User Group Sub-Committee

## Description:
Form an official sub-committee that is officially dedicated to supporting user groups.
 
## Measure of impact:
Grow and support active user groups, membership, and active attendance at .NET user groups across the globe. In addition, we would organize a monthly town-hall meeting to inform and listen to our organizers.

## Requested Budget:
No budget! If anything, this team will streamline meetup pro.

## Size of Committee Requested:
3-4 volunteers

## Which Goal and Priority is this project aligned with:
- Outreach committee to support and grow the .NET community.

## How will we know this outreach is successful?
- List of active user groups grow by 10%
- Triage and trim non-active user groups
- List of RSVPs grow by 10%, 
- Monthly meeting engaging with 50% of organizers

**Comment by shawnwildermuth** [comment]
I'd like to see if @DaveNoderer59 and the others on his team would want to help with this. I think it's a great idea!

**Comment by codehippie1** [comment]
@jamesmontemagno - Nicole Miller mentioned in last outreach meeting about the mailchimp list for the Meetup organizers. If we have that data available, If that list can be shared, I can initiate a conversation, keeping everyone in the loop to get an update on the status of their groups.

**Comment by jglozano** [comment]
Just my two cents here, adding a sub committee seems a bit of over kill. Why not have the committee do this as a goal?

**Comment by jamesmontemagno** [comment]
@jglozano I would like this sub-committee to meet more often maybe even every week and then report back up to the main committee. There is a plethora of work to be done here.

**Comment by jongalloway** [comment]
@jglozano Yeah, we talked about this a bit in the last outreach meeting. The outreach committee has a lot of different goals and activities in discussion. We were thinking that we could form a targeted, hands on team to focus specifically on user group support. The outreach committee approves and oversees, the user group subcommittee would get stuff done and report to the outreach committee.

**Comment by jglozano** [comment]
@jongalloway Yeah, I like the idea of the objectives for user groups. To me, explicitly calling it a subcommittee seems a bit too "heavy." Other committees have sub teams that handle diff aspects of what they do - ie, marketing has promotion, website, spotlights, etc., but no specific subcommittee for each.

**Comment by jglozano** [comment]
Yeah, having a group of people focusing on it is good. I was just saying that it can be something that the committee just does without a formal name.

**Comment by jamesmontemagno** [comment]
@codehippie1 this would be a different topic and part of outreaching to user groups to let them know they can submit. The virtual user group is open in for user groups, so they need to submit in. I also believe we will see a downward trend as things start to re-open and eventually the virtual user group should cease to exist IMHO.

**Comment by JaySing** [comment]
Hey folks, having several years of Xamarin community development under my belt, this is really close to my heart and I would love to be part of the committee  :)

**Comment by codehippie1** [comment]
@JaySing This is Aneesh. We had small chat over LinkedIn when I was looking for speakers for my event, and you helped me. What a small world! :-)

**Comment by jamesmontemagno** [comment]
@NicoleMillerDNF would you be up to join in atleast the first few meetings perhaps?

**Comment by nicoleabuhakmeh** [comment]
> @NicoleMillerDNF would you be up to join in atleast the first few meetings perhaps?

Do we have a time set for the meeting?

**Comment by jamesmontemagno** [comment]
@nicoleabuhakmeh I will put together an email with a calendarly to pick a time that works for everyone.

**Comment by nicoleabuhakmeh** [comment]
Hey @codehippie1 - I know James was going to put together a Google Doc together with all of the notes.  Here are the ones I sent him at the end of the meeting. Once he gets the doc out, we can work on connecting with the groups in different formats. 

Notes from Outreach Committee  Group Meeting sub-committee
 
Goal: Engage with the Virtual Meetup groups
 
Virtual User Group clean up discussion of groups not having events
In-combo with Outreach Committee
 
User group Email/ Engagement about the use and check-in on the state/health of their user groups. 
 
Promote via:
Send a blast to everybody through Meetup.
Send a blast to organizers through Mailchimp.
Post on the .NET Foundation Blog.
Post on Github Home Repo.
 
Content: TBD
 
 
Swag giveaway: Send boxes to organizers to give away?
 
Organizer on a call, and a Q&A via Streamyard or another platform. 
 
Once engagement has been completed in about 120 days, we will then work on the realigning of the groups if needed.

**Comment by jamesmontemagno** [comment]
I figure we can use GitHub for all notes -> https://github.com/dotnet-foundation/wg-outreach/pull/61 put them in there

**Comment by jamesmontemagno** [comment]
Closing this as we have set this up and are meeting regularly.
