### ISSUE TITLE
Outreach membership link is not working

### ISSUE THREAD

**Issue by codehippie1** [dotnet-foundation/wg-outreach#51]
dotnet-foundation outreach member link is not working

Url: https://github.com/orgs/dotnet-foundation/teams/outreach/members

**Comment by shawnwildermuth** [comment]
Can you add a screenshot of what you're seeing? It is working for me.

**Comment by codehippie1** [comment]
![image](https://user-images.githubusercontent.com/18332214/153515748-0b076664-5cc8-4a8c-a8da-bb3efb4b21dc.png)

**Comment by codehippie1** [comment]
@shawnwildermuth Could it be that - it is working only for members? I am getting 404 at the teams url as well: https://github.com/dotnet-foundation/teams

**Comment by shawnwildermuth** [comment]
Probably, let me see the best way to handle this.

**Comment by shawnwildermuth** [comment]
There isn't an easy way to to do this, so i've added an issue template for requesting membership:

https://github.com/dotnet-foundation/wg-outreach/issues/new?assignees=shawnwildermuth&labels=membership&template=membership.md

**Comment by jamesmontemagno** [comment]
I think it only works for members... so maybe we just need to make that clear...

**Comment by codehippie1** [comment]
@shawnwildermuth @jamesmontemagno Submitted a membership requested using the new issue template
