### ISSUE TITLE
Uneven user growth on individual meetups V/s .net virtual user group

### ISSUE THREAD

**Issue by codehippie1** [dotnet-foundation/wg-outreach#54]
## Title: 
Uneven user growth on individual meetups V/s .net virtual user group

## Description:
 When you submit an event via the "promote event" form, it creates an event in the .net Virtual meetup group meetup - https://www.meetup.com/dotnet-virtual-user-group, (assuming using meetup api), instead of deep linking to actual event listing. This does not promote user growth on original group(the group which host the actual event), but add attendees/users to the virtual meetup.

Proposed solution - 
- We should look into meetup apis and should fetch upcoming events from .net groups and should show that using a small UI/web application, or even better - display it on a outreach section of .net foundation website.
- Each of the listing click should redirect user to original event listing thus promoting organic user growth to that specific group.
- Remove ability to RSVP on an event on .NET virtual user group meetup

## Measure of impact:
-

## Requested Budget:
$0

## Size of Committee Requested:
1-3

## Which Goal and Priority is this project aligned with:
Grow users in individual .net foundation meetups, instead of accumulating them in one meetup group 

## How will we know this outreach is successful?
We can collect some analytics using Segment/App Insights to see outgoing traffic to individual user groups. Since meetup is a third party entity, unsure if specific RSVPs originating from external links(in this case, the web app) can be tracked.

**Comment by codehippie1** [comment]
@jamesmontemagno Makes sense, users from all over the country joining a NYC group would not yield benefits once in-person meets returns.

Still - we should have some form/mechanism to promote user growth on individual user groups(Users from group's geographical location). Can we add additional information to the event description in lines of

"
This [Virtual] session is run by the 'NYC Mobile .NET Developers group" that hosts meetups in Manhattan, New York City, NY, USA: [https://www.meetup.com/nycmobiledev]. If you would like to join in-person events in New York City, you should definitely check this meetup out. Direct link to the meetup is - [https://www.meetup.com/nycmobiledev]
"

I am sure, this can be added as all these info is already collected as part of event submission Form

**Comment by jamesmontemagno** [comment]
Yes, that should be done automatically as we should promote the original when someone creates the meetup event.

@DaveNoderer59 to check on that.

**Comment by DaveNoderer59** [comment]
That is the intent. To include the original link

Dave Noderer
.Net Software Developer, SQL Expert
Cell: 954-270-1186
.Net, SQL, Azure, Dynamics 365 CRM, IOT
________________________________

**Comment by jamesmontemagno** [comment]
Yup, I just checked the events and they do this. I think we can close this issue @shawnwildermuth

**Comment by codehippie1** [comment]
Closing as per @jamesmontemagno 's comment and resolution
