### ISSUE TITLE
Automated email on event submission comes with plain html

### ISSUE THREAD

**Issue by codehippie1** [dotnet-foundation/wg-outreach#56]
## Issue Title: 
Automated email on event submission comes with plain html. See screenshot.

## Issue Description:
Automated email on event submission comes with plain html. Event organizer expects a well formatted email with confirmation and next steps after event submission.

![image](https://user-images.githubusercontent.com/18332214/153672065-e4b59710-b266-4908-bc6c-c4e6c7533fd5.png)

**Comment by jamesmontemagno** [comment]
@jongalloway ?

**Comment by jongalloway** [comment]
Looking at this. It shows up formatted for me in Outlook:

![image](https://user-images.githubusercontent.com/68539/153680582-27d38b92-c09d-4aa8-8481-751eb012696c.png)

**Comment by jongalloway** [comment]
I edited the flow that generates these to re-enter the HTML tags and sent the previous e-mail again, can you check it?

**Comment by codehippie1** [comment]
Checked. Better - Attached is the screenshot
One small thing though - Line feeds are not working correctly (E.g. each of the lines in speaker bio was in a separate line)
![image](https://user-images.githubusercontent.com/18332214/153684420-ce536422-a321-4fb8-9b1f-86d0a424543e.png)

**Comment by jamesmontemagno** [comment]
Should be able to close @shawnwildermuth

**Comment by jongalloway** [comment]
I added <pre> tags around the abstract, but it's going to be hit and miss with HTML in e-mail. I agree, this should probably be closed.
