### ISSUE TITLE
Addition to the speaker directory is not working

### ISSUE THREAD

**Issue by codehippie1** [dotnet-foundation/wg-outreach#65]
I submitted profile to be added to the .NET Foundation speaker directory a few months ago.

Expectation: I should have received a confirmation/submission email with submission info and next steps/timelines

Actual: No confirmation email or updates for several months. It is likely that the form could be broken

**Comment by shawnwildermuth** [comment]
Form is working. We don't email confirmation. It's all done through github. Look at your issues to see if you find the issue created when you added your profile. If you don't find it, it wasn't submitted to us. Let me know

**Comment by codehippie1** [comment]
@shawnwildermuth 
I see my mistake, I saw now that I didn't go through the PR process.
I submitted again, After submitting, I forked the "website" and created a pull request to add to the speaker directory.
