### ISSUE TITLE
Membership Request - Jason Von Ruden

### ISSUE THREAD

**Issue by jvonruden** [dotnet-foundation/wg-outreach#66]
## Your name: 
Jason Von Ruden

## Your Github Name or Email: 
jvonruden

## Notes:
Member of the .NET foundation since the beginning.  I am the President of the Wisconsin .NET User group with monthly meetings (even thru the 2020-present pandemic!) on .NET for the last 20 years: since February 12, 2002; formed one day before the the official NET release. 

https://www.wi-ineta.org/
https://www.meetup.com/wisconsin-net-users-group/
 
Thanks,

Jason Von Ruden

**Comment by shawnwildermuth** [comment]
It says you're already a member.
