### ISSUE TITLE
Request to be Added to the Outreach Working Group

### ISSUE THREAD

**Issue by Virifortissimi** [dotnet-foundation/wg-outreach#67]
## Your name: 
Gabriel Eghosa Emmanuel

## Your Github Name or Email: 
Virifortissimi

## Notes (OPTIONAL):
I am very excited about meeting and helping new dotnet developers. I am also enthusiastic about the opportunity of doing this on a much bigger scale. Hope to hear from the team soon

**Comment by shawnwildermuth** [comment]
Added.
