### ISSUE TITLE
Sophie Obomighie request to join the outreach team.

### ISSUE THREAD

**Issue by Ochuwa-sophie** [dotnet-foundation/wg-outreach#68]
## Your name: 
Sophie Obomighie

## Your Github Name or Email: 
Sophiecodes@gmail.com

## Notes (OPTIONAL):
I am interested in joining the effort in making .net more accessible .

**Comment by shawnwildermuth** [comment]
Done...welcome!

**Comment by Ochuwa-sophie** [comment]
Thank you, Shawn.
