### ISSUE TITLE
Membership request

### ISSUE THREAD

**Issue by zako16** [dotnet-foundation/wg-outreach#71]
## Your name: 
Meerim

## Your Github Name or Email: 
GitHub: zako16, Email: meerim.zhanuzakova@gmail.com

## Notes (OPTIONAL):
_Anything you'd like us to know about why you're joining the Outreach Working Group_

**Comment by zako16** [comment]
Any updates? @shawnwildermuth

**Comment by nicoleabuhakmeh** [comment]
Hi there, 

I will forward you an invite to the Outreach committee. 

Thank you,
Nicole
