### ISSUE TITLE
Request for Outreach Working Group Membership

### ISSUE THREAD

**Issue by xlibraries** [dotnet-foundation/wg-outreach#75]
## Your name: 
Aman Agrawal

## Your Github Name or Email: 
xlibraries
## Notes (OPTIONAL):
_Anything you'd like us to know about why you're joining the Outreach Working Group_

**Comment by shawnwildermuth** [comment]
I'm not longer involved in the working group. I'm going to remove my assignment. Please reach out to @jguadagno

**Comment by xlibraries** [comment]
> ## Your name:
> Aman Agrawal
> 
> ## Your Github Name or Email:
> xlibraries
> 
> ## Notes (OPTIONAL):
> _Anything you'd like us to know about why you're joining the Outreach Working Group_

#49

**Comment by xlibraries** [comment]
> ## Your name:
> Aman Agrawal
> 
> ## Your Github Name or Email:
> xlibraries
> 
> ## Notes (OPTIONAL):
> _Anything you'd like us to know about why you're joining the Outreach Working Group_
