### ISSUE TITLE
COVID19 support for meetups in the Meetup .NET Pro network

### ISSUE THREAD

**Issue by benjaminhowarth1** [dotnet-foundation/wg-outreach#8]
Meetup organisers need a way to be able to take their event virtual quickly & easily.

I suggest setting up a channel per geographic meetup, which we then make the local event organisers a channel admin of. This way, each meetup gets a dedicated channel link to share with attendees, it's covered under the existing .NET Foundation org, and keeps our administration low.

There are 351 meetups registered under the network, so that's 351 channels. I've set up a Google Form to get organiser information, plus the name of each meetup, ready to set up the channels.

Form can be found here: https://forms.gle/S7MNYqBP8hUwn7w79

**Comment by SaraJo** [comment]
@benjaminhowarth1, I'm about to open another issue regarding this. Would love to incorporate your work as well. Would you be free to help/can we use your form as a jumping off point?

**Comment by benjaminhowarth1** [comment]
Of course! @clairernovotny also has a Mailchimp list of .NET Meetup organisers.
I've experimented with streaming & Restream.io seemed to work pretty well, as it allows multiple options for streaming (Twitter, Twitch, YouTube, and RTMP - crucially, which Teams supports for live events).

**Comment by clairernovotny** [comment]
I'm going to close this one so that we can continue the conversation in https://github.com/dotnet-foundation/wg-outreach/issues/10
