### ISSUE TITLE
Desire to join the group

### ISSUE THREAD

**Issue by xlibraries** [dotnet-foundation/wg-outreach#80]
## Your name: 
Aman Agrawal

## Your GitHub Name or Email: 
xlibraries

## Notes (OPTIONAL):
Let it  be  x ;)  just a curious head want to learn, contribute back and grow with communities

**Comment by jguadagno** [comment]
@xlibraries I can add you to meetings.  We meet on the second Monday of every month at 11:00am (UTC -7)

**Comment by xlibraries** [comment]
Would love to join them:)
It was reffered in dotnet foudation Educational Committee from Madison Hardy

**Comment by jguadagno** [comment]
Cool.  Send me your email (joseph.guadagno at dotnetfoundation dot org) or Madison so I can get you added to the meeting.

**Comment by xlibraries** [comment]
Hello Joseph,
Aman here please add this email I'd to the meeting.

Thanks & Regards,
Aman Agrawal

**Comment by xlibraries** [comment]
Done sent a mail to your email I'd 👍🏻

**Comment by xlibraries** [comment]
Recceived the invite from Madison for 2nd Monday of June :)

Thank-you for the invite closing this pull request!
