### ISSUE TITLE
Requst to join

### ISSUE THREAD

**Issue by tonyqus** [dotnet-foundation/wg-outreach#87]
## Your name: 
_Tony Qu_

## Your GitHub Name or Email: 
_https://github.com/tonyqus_

## Notes (OPTIONAL):
I'd like to join the outreach meeting and discuss my idea about a new event called .NET Open Conf

**Comment by nicoleabuhakmeh** [comment]
Hi Tony - I sent the invite to the meeting to your email listed in your bio. The next meeting is on July 10th!

**Comment by tonyqus** [comment]
Thank you!
