### ISSUE TITLE
DNF Summit September 12th 2023 - Planning

### ISSUE THREAD

**Issue by nicoleabuhakmeh** [dotnet-foundation/wg-outreach#88]
Adding members from July's meeting.  

Updates needed to the website and planning notes to collaborate on. 

Link for promotion to DNF members, projects and sponsors to submit sessions to upcoming dates: 
[DNF CFP Submission Form](https://forms.office.com/r/h8zNwGRpNr)

Date to close the submissions for September: August 11
Date to notify submitters: about a month before event, August 15
Office hour for meet and greet/questions: week before event, September 5
Streamyard tech-check in: Day before event, September 11
Event day: September 12

Host for the September 12th: Joe Guadagno (Kevin Griffin, checking on his availability)
Board Members Welcome: Any and all that are available to join
Session 1: 
Session 2:
Session 3:
Session 4:
Session 5:
Keynote:

Invited members to [Summit Website Repo](https://github.com/dotnet-foundation/summit-website)
 
Next steps are selecting sessions and planning logistics for the day at the August Outreach meeting on August 14th. 
Updates would be needed to the website after the meeting.

**Comment by jguadagno** [comment]
@nicoleabuhakmeh Can you please all me to the Summit Website Repo?

**Comment by Ellerbach** [comment]
@nicoleabuhakmeh we will be happy with @josesimoes to deliver a session on .NET nanoFramework :-)

**Comment by codehippie1** [comment]
@nicoleabuhakmeh  The source code states the site is in "Announcement" state. If I remember correctly, this is updated manually by @jglozano at deployed appsettings.json

@jglozano : Would you be able to help?

**Comment by jguadagno** [comment]
I'll take care of it in a few minutes

**Comment by jguadagno** [comment]
Done and published
