### ISSUE TITLE
Updating Dot Net Foundation SkillUp in Aba, Nigeria

### ISSUE THREAD

**Issue by davidconoh** [dotnet-foundation/wg-outreach#91]
## Title: 
_Proposal: New Dot Net SkillUp Workshops for Aba, Nigeria 2023_

## Description:
_After introducing the Dot Net ecosystem and rock-solid training kits to software developers in Aba, Nigeria, it's been a buzz in the city and its environs to improve in such a degree as to tackle local social issues using the frameworks. As a result, we have built a community welcoming new members, stakeholders and businesses looking to refresh the computing industry here, once again. Looking to host a couple more workshops to solidify the year._
 
## Measure of impact:
_100 students [between October, 2023 and December, 2023]_

## Requested Budget:
_e.g. $500_

## Size of the Committee Requested:
_2 volunteers_

## Which Goal and Priority is this project aligned with:
- _This project is aligned with the Foundation's Outreach Committee mission to equip software developers in Africa with modern skills and a safe peer-learning environment. More details can be found [here](https://www.meetup.com/aba-microsoft-user-hangout/): [https://www.meetup.com/aba-microsoft-user-hangout/](https://www.meetup.com/aba-microsoft-user-hangout/)

## How will we know this outreach is successful?
_The success of this project can be measured by how many Dot Net Developers we can train remotely [with Dot Net upskilling materials] by the end of the year, 2023._

**Comment by jguadagno** [comment]
@davidconoh What do you need from the Foundation?  How can we help?

**Comment by davidconoh** [comment]
@jguadagno It's been a month or there abouts since this issue was filed. Looks like we may need a kind review or a way to fund contributions in Aba, Nigeria??

**Comment by nicoleabuhakmeh** [comment]
Hi @davidconoh I want to direct you back to Joe's question about what you are looking for when it comes to how the Foundation can support your mission. 

You mentioned upskilling materials for .NET, there is something directly from Microsoft that can be found here: [https://dotnet.microsoft.com/en-us/learn](https://dotnet.microsoft.com/en-us/learn)

Can you elaborate on the rest of the proposal?

**Comment by davidconoh** [comment]
Hi @nicoleabuhakmeh it's nice to check up once in a while on foundation updates. However, with frameworks in a bubble at the current, this discussion thread have slightly lingered now into new costs... and the market, needs are presently volatile, I suppose.

**Comment by davidconoh** [comment]
This project and communications are now directed towards depriving a contributor of his legally defined digital rights... I thought it was the US of A?!
